#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Para + Tartma: 50 yeni orta/zor soru ekler (131-180)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW_PATH = ROOT / "data" / "para-tartma-gemini-raw.json"

NEW_QUESTIONS = [
    # --- PARA 131-155 (25 soru) ---
    {
        "id": "mat3_para_tartma_131",
        "level": "orta",
        "premise": None,
        "text": "Kumbaramdan 2 tane 20 TL, 1 tane 10 TL ve 3 tane 5 TL çıktı. Kumbaramda toplam kaç TL vardır?",
        "correct": "65 TL",
        "wrong1": "55 TL",
        "wrong2": "70 TL",
        "explanation": "20 + 20 = 40 TL. 10 TL eklersek 50 TL. 3 tane 5 TL = 15 TL. Toplam: 50 + 15 = 65 TL.",
    },
    {
        "id": "mat3_para_tartma_132",
        "level": "orta",
        "premise": None,
        "text": "Cebimde 6 tane 25 kuruş var. Bu paraların toplam değeri ne kadar eder?",
        "correct": "1 TL 50 kr",
        "wrong1": "1 TL",
        "wrong2": "2 TL",
        "explanation": "6 x 25 = 150 kuruş eder. 150 kuruş = 1 TL 50 kuruştur.",
    },
    {
        "id": "mat3_para_tartma_133",
        "level": "orta",
        "premise": None,
        "text": "3 TL 60 kr ile 2 TL 45 kr toplandığında sonuç ne olur?",
        "correct": "6 TL 5 kr",
        "wrong1": "5 TL 95 kr",
        "wrong2": "6 TL 50 kr",
        "explanation": "Liralar: 3 + 2 = 5 TL. Kuruşlar: 60 + 45 = 105 kr = 1 TL 5 kr. Toplam: 6 TL 5 kr.",
    },
    {
        "id": "mat3_para_tartma_134",
        "level": "zor",
        "premise": None,
        "text": "Tanesi 18 TL olan oyuncaklardan cebimdeki 85 TL ile EN FAZLA kaç tane alabilirim?",
        "correct": "4",
        "wrong1": "5",
        "wrong2": "3",
        "explanation": "18, 36, 54, 72 TL ile 4 tane alınabilir. 5 tane 90 TL tutar, paramız yetmez.",
    },
    {
        "id": "mat3_para_tartma_135",
        "level": "orta",
        "premise": None,
        "text": "Cüzdanımda 1 tane 50 TL, 1 tane 20 TL ve 2 tane 10 TL var. Toplam kaç TL param vardır?",
        "correct": "90 TL",
        "wrong1": "80 TL",
        "wrong2": "100 TL",
        "explanation": "50 + 20 = 70 TL. 2 tane 10 TL = 20 TL. Toplam: 70 + 20 = 90 TL.",
    },
    {
        "id": "mat3_para_tartma_136",
        "level": "zor",
        "premise": None,
        "text": "5 arkadaş 125 TL'lik yemek hesabını eşit paylaştı. Kişi başı kaç TL öder?",
        "correct": "25 TL",
        "wrong1": "30 TL",
        "wrong2": "20 TL",
        "explanation": "Eşit paylaşım bölme işlemidir. 125 ÷ 5 = 25 TL.",
    },
    {
        "id": "mat3_para_tartma_137",
        "level": "orta",
        "premise": None,
        "text": "4 tane 10 kuruş ile 6 tane 50 kuruş toplandığında değer olarak ne kadar eder?",
        "correct": "3 TL 40 kr",
        "wrong1": "3 TL",
        "wrong2": "4 TL",
        "explanation": "4 x 10 = 40 kr. 6 x 50 = 300 kr. Toplam: 340 kr = 3 TL 40 kr.",
    },
    {
        "id": "mat3_para_tartma_138",
        "level": "zor",
        "premise": None,
        "text": "Kumbaramdaki paranın 3/5'ini harcadım, geriye 24 TL kaldı. Başlangıçta kumbaramda kaç TL vardı?",
        "correct": "60 TL",
        "wrong1": "40 TL",
        "wrong2": "36 TL",
        "explanation": "Harcanmayan kısım 2/5'tir. 2/5 = 24 TL ise tamamı: 24 ÷ 2 x 5 = 60 TL.",
    },
    {
        "id": "mat3_para_tartma_139",
        "level": "orta",
        "premise": None,
        "text": "Kilosu 14 TL olan muzdan yarım kilo aldım. Manava kaç TL öderim?",
        "correct": "7 TL",
        "wrong1": "14 TL",
        "wrong2": "28 TL",
        "explanation": "Yarım kilo alınca fiyat da yarıya düşer: 14 ÷ 2 = 7 TL.",
    },
    {
        "id": "mat3_para_tartma_140",
        "level": "zor",
        "premise": None,
        "text": "Fiyatı 88 TL olan oyuncak için 35 TL'm var. Günde 4 TL biriktirirsem eksik paramı kaç günde tamamlarım?",
        "correct": "14",
        "wrong1": "13",
        "wrong2": "12",
        "explanation": "Eksik para: 88 - 35 = 53 TL. 53 ÷ 4 = 13, kalan 1 TL için bir gün daha gerekir. Toplam 14 gün.",
    },
    {
        "id": "mat3_para_tartma_141",
        "level": "orta",
        "premise": None,
        "text": "250 kuruş, 1 TL 25 kuruş ve 2 TL toplandığında sonuç ne olur?",
        "correct": "5 TL 75 kr",
        "wrong1": "4 TL 75 kr",
        "wrong2": "6 TL",
        "explanation": "250 kr = 2 TL 50 kr. 1 TL 25 kr eklersek 3 TL 75 kr. 2 TL daha: 5 TL 75 kr.",
    },
    {
        "id": "mat3_para_tartma_142",
        "level": "zor",
        "premise": None,
        "text": "3 tane 50 kuruş ile 5 tane 1 TL toplandığında değer olarak ne kadar eder?",
        "correct": "6 TL 50 kr",
        "wrong1": "5 TL 50 kr",
        "wrong2": "7 TL",
        "explanation": "3 x 50 = 150 kr = 1 TL 50 kr. 5 x 1 TL = 5 TL. Toplam: 6 TL 50 kr.",
    },
    {
        "id": "mat3_para_tartma_143",
        "level": "orta",
        "premise": None,
        "text": "Tanesi 22 TL olan defterden 2 tane alıp kasiyere 50 TL verdim. Kaç TL para üstü alırım?",
        "correct": "6 TL",
        "wrong1": "8 TL",
        "wrong2": "4 TL",
        "explanation": "2 defter: 2 x 22 = 44 TL. Para üstü: 50 - 44 = 6 TL.",
    },
    {
        "id": "mat3_para_tartma_144",
        "level": "zor",
        "premise": None,
        "text": "Kardeşim benden 8 TL daha fazla harçlık alıyor. İkimizin toplam harçlığı 62 TL ise benim harçlığım kaç TL'dir?",
        "correct": "27 TL",
        "wrong1": "30 TL",
        "wrong2": "34 TL",
        "explanation": "Kardeşimin harçlığı: 27 + 8 = 35 TL. Toplam: 27 + 35 = 62 TL.",
    },
    {
        "id": "mat3_para_tartma_145",
        "level": "orta",
        "premise": None,
        "text": "Cüzdanımda 1 tane 100 TL, 1 tane 50 TL ve 2 tane 20 TL var. Toplam kaç TL param vardır?",
        "correct": "190 TL",
        "wrong1": "170 TL",
        "wrong2": "200 TL",
        "explanation": "100 + 50 = 150 TL. 2 x 20 = 40 TL. Toplam: 150 + 40 = 190 TL.",
    },
    {
        "id": "mat3_para_tartma_146",
        "level": "zor",
        "premise": None,
        "text": "Düzinesi 48 TL olan kurşun kalemlerin 1 tanesi kaç TL'dir?",
        "correct": "4 TL",
        "wrong1": "6 TL",
        "wrong2": "3 TL",
        "explanation": "1 düzine 12 tanedir. 48 ÷ 12 = 4 TL.",
    },
    {
        "id": "mat3_para_tartma_147",
        "level": "orta",
        "premise": None,
        "text": "400 kuruş ile 350 kuruş toplandığında sonuç ne olur?",
        "correct": "7 TL 50 kr",
        "wrong1": "750 kr",
        "wrong2": "8 TL",
        "explanation": "400 + 350 = 750 kuruş eder. 750 kr = 7 TL 50 kr.",
    },
    {
        "id": "mat3_para_tartma_148",
        "level": "zor",
        "premise": None,
        "text": "Tanesi 25 kuruş olan sakızlardan 8 tane aldım. Bakkala toplam kaç TL öderim?",
        "correct": "2 TL",
        "wrong1": "4 TL",
        "wrong2": "1 TL",
        "explanation": "8 x 25 = 200 kuruş eder. 200 kr = 2 TL.",
    },
    {
        "id": "mat3_para_tartma_149",
        "level": "orta",
        "premise": None,
        "text": "2 tane 1 TL, 3 tane 50 kuruş ve 1 tane 25 kuruş toplandığında değer olarak ne kadar eder?",
        "correct": "4 TL 25 kr",
        "wrong1": "3 TL 75 kr",
        "wrong2": "4 TL 50 kr",
        "explanation": "2 TL + (3 x 50 = 150 kr = 1 TL 50 kr) + 25 kr = 4 TL 25 kr.",
    },
    {
        "id": "mat3_para_tartma_150",
        "level": "zor",
        "premise": None,
        "text": "Marketten 35 TL, 28 TL ve 19 TL tutan üç ürün aldım. Kasaya 100 TL verirsem kaç TL para üstü alırım?",
        "correct": "18 TL",
        "wrong1": "28 TL",
        "wrong2": "8 TL",
        "explanation": "Toplam: 35 + 28 + 19 = 82 TL. Para üstü: 100 - 82 = 18 TL.",
    },
    {
        "id": "mat3_para_tartma_151",
        "level": "orta",
        "premise": None,
        "text": "Kilosu 12 TL olan biberden 3 kilogram alan bir müşteri manava kaç TL öder?",
        "correct": "36 TL",
        "wrong1": "24 TL",
        "wrong2": "48 TL",
        "explanation": "Kilo ile fiyatı çarparız: 3 x 12 = 36 TL.",
    },
    {
        "id": "mat3_para_tartma_152",
        "level": "zor",
        "premise": None,
        "text": "Yarım düzinesi 18 TL olan yumurtaların 1 tanesi kaç TL'dir?",
        "correct": "3 TL",
        "wrong1": "6 TL",
        "wrong2": "2 TL",
        "explanation": "Yarım düzine 6 tanedir. 18 ÷ 6 = 3 TL.",
    },
    {
        "id": "mat3_para_tartma_153",
        "level": "orta",
        "premise": None,
        "text": "Babam 70 TL, annem 45 TL verdi. Birlikte 95 TL harcadık. Geriye kaç TL paramız kaldı?",
        "correct": "20 TL",
        "wrong1": "30 TL",
        "wrong2": "10 TL",
        "explanation": "Toplam para: 70 + 45 = 115 TL. Kalan: 115 - 95 = 20 TL.",
    },
    {
        "id": "mat3_para_tartma_154",
        "level": "zor",
        "premise": None,
        "text": "5 TL 90 kr ile 3 TL 15 kr toplandığında sonuç ne olur?",
        "correct": "9 TL 5 kr",
        "wrong1": "8 TL 95 kr",
        "wrong2": "9 TL 50 kr",
        "explanation": "Liralar: 5 + 3 = 8 TL. Kuruşlar: 90 + 15 = 105 kr = 1 TL 5 kr. Toplam: 9 TL 5 kr.",
    },
    {
        "id": "mat3_para_tartma_155",
        "level": "orta",
        "premise": None,
        "text": "Fiyatı 95 TL olan ayakkabı indirimle 78 TL oldu. Ayakkabıya kaç TL indirim yapılmıştır?",
        "correct": "17 TL",
        "wrong1": "27 TL",
        "wrong2": "13 TL",
        "explanation": "95 - 78 = 17 TL indirim yapılmıştır.",
    },
    # --- TARTMA 156-180 (25 soru) ---
    {
        "id": "mat3_para_tartma_156",
        "level": "orta",
        "premise": None,
        "text": "750 gram ile 250 gram toplandığında sonuç kaç kilogram eder?",
        "correct": "1 kg",
        "wrong1": "2 kg",
        "wrong2": "500 g",
        "explanation": "750 + 250 = 1000 gram eder. 1000 gram = 1 kilogramdır.",
    },
    {
        "id": "mat3_para_tartma_157",
        "level": "orta",
        "premise": None,
        "text": "1 kilogram peynirden 375 gram yedik. Geriye kaç gram peynir kalmıştır?",
        "correct": "625 g",
        "wrong1": "675 g",
        "wrong2": "525 g",
        "explanation": "1 kg = 1000 gramdır. 1000 - 375 = 625 gram kalmıştır.",
    },
    {
        "id": "mat3_para_tartma_158",
        "level": "zor",
        "premise": None,
        "text": "Boşken 400 gram gelen bir kutu, çikolata ile doluyken 2 kg 400 gram geliyor. Kutunun içindeki çikolata net kaç gramdır?",
        "correct": "2000 g",
        "wrong1": "2400 g",
        "wrong2": "1800 g",
        "explanation": "Dolu ağırlık: 2400 gram. Boş kutu: 400 gram. Net çikolata: 2400 - 400 = 2000 gram.",
    },
    {
        "id": "mat3_para_tartma_159",
        "level": "orta",
        "premise": None,
        "text": "Her biri 2 kilogram olan un torunlarından 4 tane taşındı. Toplam taşınan yük kaç kilogramdır?",
        "correct": "8 kg",
        "wrong1": "6 kg",
        "wrong2": "10 kg",
        "explanation": "4 x 2 = 8 kilogram eder.",
    },
    {
        "id": "mat3_para_tartma_160",
        "level": "zor",
        "premise": None,
        "text": "Dengede olan bir terazinin sol kefesinde 3 kg 250 gram ağırlık vardır. Sağ kefesinde 1 kg 750 gram ağırlık ve bir kavun vardır. Kavun kaç gramdır?",
        "correct": "1500 g",
        "wrong1": "1000 g",
        "wrong2": "2000 g",
        "explanation": "Sol kefe: 3250 gram. Sağ kefede 1750 gram var. Kavun: 3250 - 1750 = 1500 gram.",
    },
    {
        "id": "mat3_para_tartma_161",
        "level": "orta",
        "premise": None,
        "text": "3 kilogram 200 gram ile 800 gram toplandığında sonuç kaç kilogram eder?",
        "correct": "4 kg",
        "wrong1": "3 kg",
        "wrong2": "5 kg",
        "explanation": "3200 + 800 = 4000 gram = 4 kilogram.",
    },
    {
        "id": "mat3_para_tartma_162",
        "level": "zor",
        "premise": None,
        "text": "Kilosu 40 TL olan zeytinden yarım kilo alan bir müşteri kaç TL öder?",
        "correct": "20 TL",
        "wrong1": "40 TL",
        "wrong2": "10 TL",
        "explanation": "Yarım kilo alınca fiyat da yarıya düşer: 40 ÷ 2 = 20 TL.",
    },
    {
        "id": "mat3_para_tartma_163",
        "level": "orta",
        "premise": None,
        "text": "Her paketi 200 gram olan bisküvilerden 5 paket alan biri toplam kaç kilogram bisküvi almış olur?",
        "correct": "1 kg",
        "wrong1": "2 kg",
        "wrong2": "Yarım kg",
        "explanation": "5 x 200 = 1000 gram. 1000 gram = 1 kilogramdır.",
    },
    {
        "id": "mat3_para_tartma_164",
        "level": "zor",
        "premise": None,
        "text": "Kamyonete 35 kg, 28 kg ve 22 kg ağırlığında üç yük kondu. Kamyonetteki toplam yük kaç kilogramdır?",
        "correct": "85 kg",
        "wrong1": "75 kg",
        "wrong2": "95 kg",
        "explanation": "35 + 28 + 22 = 85 kilogram eder.",
    },
    {
        "id": "mat3_para_tartma_165",
        "level": "orta",
        "premise": None,
        "text": "Tartıda 1200 gram gelen bir koli meyve kaç kilogramdır?",
        "correct": "1 kg 200 g",
        "wrong1": "12 kg",
        "wrong2": "120 kg",
        "explanation": "1200 gram = 1 kilogram 200 gramdır.",
    },
    {
        "id": "mat3_para_tartma_166",
        "level": "zor",
        "premise": None,
        "text": "Depodaki 48 kg şekeri her biri 6 kg alabilen çuvallara dolduracağız. Kaç çuval gerekir?",
        "correct": "8 çuval",
        "wrong1": "6 çuval",
        "wrong2": "9 çuval",
        "explanation": "48 ÷ 6 = 8 çuval gerekir.",
    },
    {
        "id": "mat3_para_tartma_167",
        "level": "orta",
        "premise": None,
        "text": "Bir pasta tarifi 250 gram un gerektirir. Aynı tariften 4 ölçü yapılırsa toplam kaç kilogram un kullanılır?",
        "correct": "1 kg",
        "wrong1": "2 kg",
        "wrong2": "Yarım kg",
        "explanation": "4 x 250 = 1000 gram = 1 kilogram.",
    },
    {
        "id": "mat3_para_tartma_168",
        "level": "zor",
        "premise": None,
        "text": "Ahmet 32 kg, Can ise 48 kg'dır. Tahterevallide dengede kalabilmeleri için Can'ın yanına kaç kilogramlık ağırlık daha konmalıdır?",
        "correct": "16 kg",
        "wrong1": "20 kg",
        "wrong2": "12 kg",
        "explanation": "Denge için iki taraf 48 kg olmalı. Can tarafına 48 - 32 = 16 kg eklenmelidir.",
    },
    {
        "id": "mat3_para_tartma_169",
        "level": "orta",
        "premise": None,
        "text": "2 yarım kilogram ile 1 çeyrek kilogram toplandığında sonuç ne olur?",
        "correct": "1 kg 250 g",
        "wrong1": "1 kg",
        "wrong2": "1 kg 500 g",
        "explanation": "2 yarım = 1 kg. 1 çeyrek = 250 g. Toplam: 1 kg 250 g.",
    },
    {
        "id": "mat3_para_tartma_170",
        "level": "zor",
        "premise": None,
        "text": "Toptancı 100 kilogram elmayı 400 TL'ye satın aldı. Elmanın 1 kilogramı kaç TL'ye gelmiştir?",
        "correct": "4 TL",
        "wrong1": "10 TL",
        "wrong2": "5 TL",
        "explanation": "1 kilogram fiyatı: 400 ÷ 100 = 4 TL.",
    },
    {
        "id": "mat3_para_tartma_171",
        "level": "orta",
        "premise": None,
        "text": "1 kilogram zeytinden 400 gram yedik. Geriye kaç gram zeytin kalmıştır?",
        "correct": "600 g",
        "wrong1": "500 g",
        "wrong2": "400 g",
        "explanation": "1000 - 400 = 600 gram kalmıştır.",
    },
    {
        "id": "mat3_para_tartma_172",
        "level": "zor",
        "premise": None,
        "text": "3 kilogram 500 gram ile 2 kilogram 750 gram toplandığında sonuç ne olur?",
        "correct": "6 kg 250 g",
        "wrong1": "5 kg 250 g",
        "wrong2": "6 kg 500 g",
        "explanation": "3500 + 2750 = 6250 gram = 6 kilogram 250 gram.",
    },
    {
        "id": "mat3_para_tartma_173",
        "level": "orta",
        "premise": None,
        "text": "Her biri 25 kilogram olan patates çuvallarından 3 tane alan bir restoran toplam kaç kilogram patates almıştır?",
        "correct": "75 kg",
        "wrong1": "50 kg",
        "wrong2": "100 kg",
        "explanation": "3 x 25 = 75 kilogram eder.",
    },
    {
        "id": "mat3_para_tartma_174",
        "level": "zor",
        "premise": None,
        "text": "Fırıncı 4 kilogram un kullandı, geriye 1 kilogram 500 gram un kaldı. Başlangıçta kaç kilogram un vardı?",
        "correct": "5 kg 500 g",
        "wrong1": "5 kg",
        "wrong2": "6 kg",
        "explanation": "Kullanılan 4 kg + kalan 1 kg 500 g = 5 kg 500 g.",
    },
    {
        "id": "mat3_para_tartma_175",
        "level": "orta",
        "premise": None,
        "text": "Çeyrek kilogramı 18 TL olan cevizden 1 kilogram alan biri kaç TL öder?",
        "correct": "72 TL",
        "wrong1": "36 TL",
        "wrong2": "54 TL",
        "explanation": "1 kilogramda 4 çeyrek vardır. 18 x 4 = 72 TL.",
    },
    {
        "id": "mat3_para_tartma_176",
        "level": "zor",
        "premise": None,
        "text": "Bir arı günde 2 gram bal üretir. Kovandaki 40 arı 3 günde toplam kaç gram bal üretir?",
        "correct": "240 g",
        "wrong1": "120 g",
        "wrong2": "360 g",
        "explanation": "40 arı günde: 40 x 2 = 80 gram. 3 günde: 80 x 3 = 240 gram.",
    },
    {
        "id": "mat3_para_tartma_177",
        "level": "orta",
        "premise": None,
        "text": "2 yarım kilogram un ile 3 çeyrek kilogram un toplandığında sonuç ne olur?",
        "correct": "1 kg 750 g",
        "wrong1": "1 kg 500 g",
        "wrong2": "2 kg",
        "explanation": "2 yarım = 1 kg. 3 çeyrek = 750 g. Toplam: 1 kg 750 g.",
    },
    {
        "id": "mat3_para_tartma_178",
        "level": "zor",
        "premise": None,
        "text": "Boş sepet 800 gram geliyor. Sepete elma konunca 5 kg 800 gram oluyor. Sepetteki elmalar net kaç kilogramdır?",
        "correct": "5 kg",
        "wrong1": "4 kg",
        "wrong2": "6 kg",
        "explanation": "5800 - 800 = 5000 gram = 5 kilogram elma vardır.",
    },
    {
        "id": "mat3_para_tartma_179",
        "level": "orta",
        "premise": None,
        "text": "4 kilogram 500 gram ağırlığındaki bir sandıktan 1 kilogram 750 gram eşya çıkarıldı. Sandıkta kaç gram eşya kalmıştır?",
        "correct": "2750 g",
        "wrong1": "3250 g",
        "wrong2": "2500 g",
        "explanation": "4500 - 1750 = 2750 gram kalmıştır.",
    },
    {
        "id": "mat3_para_tartma_180",
        "level": "zor",
        "premise": None,
        "text": "Manavdan kilosu 8 TL olan domatesten 2 kg, kilosu 12 TL olan biberden 3 kg aldım. Toplam kaç TL öderim?",
        "correct": "52 TL",
        "wrong1": "44 TL",
        "wrong2": "60 TL",
        "explanation": "Domates: 2 x 8 = 16 TL. Biber: 3 x 12 = 36 TL. Toplam: 16 + 36 = 52 TL.",
    },
]


def main() -> int:
    data = json.loads(RAW_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit("Raw JSON liste olmalı")
    existing = {q["id"] for q in data}
    for q in NEW_QUESTIONS:
        if q["id"] in existing:
            raise SystemExit(f"Zaten var: {q['id']}")
    data.extend(NEW_QUESTIONS)
    RAW_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"OK: {len(NEW_QUESTIONS)} soru eklendi. Toplam: {len(data)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
