# -*- coding: utf-8 -*-
"""3. sınıf Cümlede Anlam — 150 soru."""
from __future__ import annotations

_RAW: list[tuple] = [
    # ── KOLAY (50) ──
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Sokaklar ıslak oldu', 'Yağmur yağdığı için', 'Yağmur yağdı', 'Yağmur yağması sebeptir; sokakların ıslanması bu sebebin sonucudur.', 'Yağmur yağdığı için sokaklar ıslak oldu.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok çalışmam', 'Yüksek not almam', 'Sınav', 'Çalışmak bir nedendir; yüksek not almak bu nedenin sonucudur.', 'Çok çalıştığım için sınavdan yüksek not aldım.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Okula gelememesi', 'Hasta olması', 'Okul', 'Hasta olmak sebeptir; okula gelemeyiş bunun sonucudur.', 'Hasta olduğu için okula gelemedi.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Geç kalması', 'Otobüsü kaçırması', 'Otobüs', 'Geç kalmak nedendir; otobüsü kaçırmak bunun sonucudur.', 'Geç kaldığı için otobüsü kaçırdı.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Çok yemek yemesi', 'Aç olması', 'Yemek', 'Açlık sebeptir; çok yemek yemek bunun sonucudur.', 'Aç olduğu için çok yemek yedi.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Soğuk hava', 'Mont giymesi', 'Hava', 'Soğuk hava nedendir; mont giymek bunun sonucudur.', 'Soğuk hava olduğu için mont giydi.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Kalemi kırması', 'Dikkatsiz davranması', 'Kalem', 'Dikkatsizlik sebeptir; kalemin kırılması bunun sonucudur.', 'Dikkatsiz davrandığı için kalemi kırdı.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok koşması', 'Yorulması', 'Koşu', 'Çok koşmak nedendir; yorulmak bunun sonucudur.', 'Çok koştuğu için yoruldu.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Lambanın sönmesi', 'Elektriğin kesilmesi', 'Elektrik', 'Elektriğin kesilmesi sebeptir; lambanın sönmesi sonuçtur.', 'Elektrik kesildiği için lamba söndü.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Susaması', 'Su içmesi', 'Su', 'Susamak nedendir; su içmek bunun sonucudur.', 'Susadığı için su içti.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Annemin yemek yapması', 'Mutfak sıcak olması', 'Mutfak', 'Yemek yapmak nedendir; mutfağın sıcak olması bunun sonucudur.', 'Annem yemek yaptı, bu yüzden mutfak sıcaktı.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Yaprakların uçması', 'Rüzgârın esmesi', 'Yapraklar', 'Rüzgâr sebeptir; yaprakların uçması sonuçtur.', 'Rüzgâr esti, bu yüzden yapraklar uçtu.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Kalemi düşürmesi', 'Kalemin kırılması', 'Kalem', 'Düşürmek nedendir; kırılma bunun sonucudur.', 'Kalemi düşürdü, bu yüzden kırıldı.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Gözlerinin dolması', 'Çok gülmek', 'Gözler', 'Çok gülmek sebeptir; gözlerin dolması sonuçtur.', 'Çok gülünce gözleri doldu.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Ödevini bitirmemesi', 'Öğretmenin uyarı vermesi', 'Ödev', 'Ödevi bitirmemek nedendir; uyarı almak sonuçtur.', 'Ödevini bitirmedi, bu yüzden öğretmen uyarı verdi.'),
    ('kolay', 'Yukarıdaki cümlede boşluğa hangi bağlaç gelmelidir?', 'için', 'ama', 'veya', 'Soğuk hava bir neden olduğu için pencereyi kapatma sonucunu anlatır.', 'Hava soğuk olduğu için pencereyi kapattık.'),
    ('kolay', 'Yukarıdaki cümlede boşluğa hangi sözcük gelmelidir?', 'için', 'ile', 'gibi', 'Yorulmak sebeptir; erken yatmak sonuçtur.', 'Çok yorulduğu için erken yattı.'),
    ('kolay', 'Yukarıdaki cümlede boşluğa hangi sözcük gelmelidir?', 'bu yüzden', 'ama', 'veya', 'Hasta olmak nedendir; doktora gitmek sonuçtur.', 'Hasta oldu, _____ doktora gitti.'),
    ('kolay', 'Yukarıdaki cümlede boşluğa hangi sözcük gelmelidir?', 'bu yüzden', 'fakat', 'ya da', 'Yağmur yağmak sebeptir; şemsiye açmak sonuçtur.', 'Yağmur yağdı, _____ şemsiyeyi açtık.'),
    ('kolay', 'Yukarıdaki cümlede boşluğa hangi sözcük gelmelidir?', 'dolayısıyla', 'ancak', 'hem de', 'Çalışmak nedendir; sınavı kazanmak sonuçtur.', 'Çok çalıştı, _____ sınavı kazandı.'),
    ('kolay', 'Hangisinde kar yağması ile okul tatili arasında sebep-sonuç vardır?', 'Kar yağınca okul tatil oldu', 'Bugün hava güzel', 'Ali okula gitti', 'Kar yağması sebeptir; okulun tatil olması sonuçtur.'),
    ('kolay', 'Hangisinde ağlama ile sesin kısılması arasında sebep-sonuç vardır?', 'Çok ağladığı için sesi kısıldı', 'Ayşe kitap okuyor', 'Bahçede çiçek var', 'Ağlamak sebeptir; sesin kısılması sonuçtur.'),
    ('kolay', 'Hangisinde sebep-sonuç ilişkisi kurulmamıştır?', 'Kedim süt içti', 'Susuz kaldığı için su içti', 'Geç kaldığı için koştu', 'Kedinin süt içmesi basit bir olaydır; neden-sonuç kurulmamıştır.'),
    ('kolay', 'Hangisinde yalnızca olay anlatılmış, sebep-sonuç yoktur?', 'Parkta top oynadık', 'Soğuktan titredi', 'Yorulduğu için dinlendi', 'Top oynamak tek başına bir eylemdir.'),
    ('kolay', 'Hangisinde elektrik kesintisi ile televizyon kapanması arasında sebep-sonuç vardır?', 'Elektrik gitti, bu yüzden televizyon kapandı', 'Televizyon büyük', 'Salon geniş', 'Elektriğin gitmesi sebeptir; televizyonun kapanması sonuçtur.'),
    ('kolay', 'Sebep nedir?', 'Bir olayın ortaya çıkmasına yol açan neden', 'Bir olayın sonunda olan şey', 'Bir cümlenin sonu', 'Sebep, bir şeyin olmasına neden olan durumdur.'),
    ('kolay', 'Sonuç nedir?', 'Sebepten sonra ortaya çıkan durum', 'Bir olayın başlangıcı', 'Cümledeki isim', 'Sonuç, sebebin ardından meydana gelen olaydır.'),
    ('kolay', 'Çünkü kelimesi cümlede neyi gösterir?', 'Sebebi', 'Sonucu', 'Zamanı', 'Çünkü kelimesi neden bildirir.'),
    ('kolay', 'Bu yüzden kelimesi cümlede neyi gösterir?', 'Sonucu', 'Sebebi', 'Yeri', 'Bu yüzden bağlacı sebepten sonra gelen sonucu anlatır.'),
    ('kolay', 'Dolayısıyla kelimesi hangi ilişkiyi kurar?', 'Sebep-sonuç', 'Karşıtlık', 'Seçenek', 'Dolayısıyla bir nedenin ardından gelen sonucu bağlar.'),
    ('kolay', 'Yukarıdaki cümlede terlemesi hangi tür cümle öğesidir?', 'Sonuç', 'Sebep', 'Özne', 'Oynamak sebeptir; terlemek bunun sonucudur.', 'Çok oynadığı için terledi.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Kışın gelmesi', 'Yaprakların dökülmesi', 'Ağaçlar', 'Kışın gelmesi nedendir; yaprakların dökülmesi sonuçtur.', 'Kış geldiği için ağaçlar yapraklarını döktü.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Boğazının ağrıması', 'Dondurma yemesi', 'Dondurma', 'Dondurma yemek sebeptir; boğaz ağrısı sonuçtur.', 'Dondurma yediği için boğazı ağrıdı.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Fırtınanın çıkması', 'Dışarı çıkamamamız', 'Dışarı', 'Fırtına sebeptir; dışarı çıkamamak sonuçtur.', 'Fırtına çıktığı için dışarı çıkamadık.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Geri dönmesi', 'Kitabı unutması', 'Kitap', 'Kitabı unutmak sebeptir; geri dönmek sonuçtur.', 'Kitabı unuttuğu için geri döndü.'),
    ('kolay', 'Yağmur ile ıslanma arasındaki doğru eşleştirme hangisidir?', 'Sebep: yağmur — Sonuç: ıslanmak', 'Sebep: ıslanmak — Sonuç: yağmur', 'Sebep: güneş — Sonuç: yağmur', 'Yağmur yağması ıslanmaya neden olur.'),
    ('kolay', 'Açlık ile yemek yeme arasındaki doğru eşleştirme hangisidir?', 'Sebep: açlık — Sonuç: yemek yemek', 'Sebep: yemek yemek — Sonuç: açlık', 'Sebep: uyku — Sonuç: açlık', 'Açlık yemek yemeye neden olur.'),
    ('kolay', 'İçin bağlacı hangi ilişkiyi kurar?', 'Sebep-sonuç', 'Karşıtlık', 'Benzerlik', 'İçin bağlacı bir neden ile sonucu birbirine bağlar.'),
    ('kolay', 'Sebep-sonuç cümlesinde önce genellikle ne gelir?', 'Sebep', 'Sonuç', 'Soru', 'Sebep genellikle önce, sonuç sonra söylenir.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Kar yağması', 'Yolların kaygan olması', 'Yollar', 'Kar yağmak nedendir; yolların kaygan olması sonuçtur.', 'Kar yağınca yollar kaygan oldu.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Erken yatması', 'Uykusunun gelmesi', 'Uyku', 'Uykunun gelmesi sebeptir; erken yatmak sonuçtur.', 'Uykusu geldiği için erken yattı.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok bağırmak', 'Sesinin kısılması', 'Ses', 'Çok bağırmak nedendir; sesin kısılması sonuçtur.', 'Çok bağırdığı için sesi kısıldı.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Dalların sallanması', 'Rüzgarın esmesi', 'Ağaç', 'Rüzgar sebeptir; dalların sallanması sonuçtur.', 'Rüzgar estiği için ağaç dalları sallandı.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Kalemi kaybetmesi', 'Yeni kalem alması', 'Kalem', 'Kalemi kaybetmek nedendir; yeni kalem almak sonuçtur.', 'Kalemi kaybettiği için yeni kalem aldı.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Çok düşünmesi', 'Sınavın zor olması', 'Sınav', 'Sınavın zor olması sebeptir; çok düşünmek sonuçtur.', 'Sınav zor olduğu için çok düşündü.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Gece geç yatmak', 'Sabah yorgun kalkmak', 'Sabah', 'Geç yatmak nedendir; yorgun kalkmak sonuçtur.', 'Gece geç yattığı için sabah yorgun kalktı.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Cildin kızarması', 'Güneşte kalmak', 'Güneş', 'Güneşte kalmak sebeptir; cildin kızarması sonuçtur.', 'Çok güneşte kaldığı için cildi kızardı.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Yorgun olması', 'Dinlenmesi', 'Anne', 'Yorgunluk sebeptir; dinlenmek sonuçtur.', 'Annem yorgun olduğu için dinlendi.'),
    ('kolay', 'Yukarıdaki cümlede sonuç hangisidir?', 'Uyanmamız', 'Köpeğin havlaması', 'Köpek', 'Köpeğin havlaması sebeptir; uyanmak sonuçtur.', 'Köpek havladığı için uyandık.'),
    ('kolay', 'Yukarıdaki cümlede sebep hangisidir?', 'Buzun kaygan olması', 'Düşmesi', 'Buz', 'Buzun kaygan olması nedendir; düşmek sonuçtur.', 'Buz kaygan olduğu için düştü.'),
    # ── ORTA (50) ──
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Kar fırtınasının çıkması', 'Okulun erken kapanması', 'Okul', 'Fırtına sebeptir; okulun erken kapanması sonuçtur.', 'Kar fırtınası çıktığı için okul erken kapandı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Notunun düşmesi', 'Ödevini zamanında yapmaması', 'Not', 'Ödevi yapmamak sebeptir; notun düşmesi sonuçtur.', 'Ödevini zamanında yapmadığı için notu düştü.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok televizyon izlemesi', 'Gözlerinin yorulması', 'Televizyon', 'Televizyon izlemek sebeptir; göz yorgunluğu sonuçtur.', 'Çok televizyon izlediği için gözleri yoruldu.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Pikniğin iptal olması', 'Yağmur yağması', 'Piknik', 'Yağmur sebeptir; pikniğin iptal olması sonuçtur.', 'Yağmur yağdığı için piknik iptal oldu.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Kalemin kırılması', 'Yeni kalem istemesi', 'Kalem', 'Kalemin kırılması sebeptir; yeni kalem istemek sonuçtur.', 'Kalemi kırıldığı için yeni kalem istedi.'),
    ('orta', 'Yukarıdaki cümlede sebep-sonuç sırası doğru mudur?', 'Evet, doğru', 'Hayır, ters', 'Sebep-sonuç yok', 'Çalışmamak sebep, düşük not sonuçtur; sıra doğrudur.', 'Çalışmadığı için sınavdan düşük not aldı.'),
    ('orta', 'Yukarıdaki cümlede sebep-sonuç ilişkisi doğru mu?', 'Hayır, yanlış', 'Evet, doğru', 'İlişki yok', 'Düşük not çalışmamanın sonucudur; sebep olarak gösterilmesi yanlıştır.', 'Sınavdan düşük not aldığı için çalışmadı.'),
    ('orta', 'Hasta olmayı sebep gösteren cümle hangisidir?', 'Okula gitmedi çünkü hasta oldu', 'Hasta oldu okula gitti', 'Okul güzel', 'Çünkü kelimesi hasta olmayı sebep olarak bildirir.'),
    ('orta', 'Aşağıdaki cümlelerden hangisinde bu yüzden sonuç bildirir?', 'Yağmur yağdı, bu yüzden ıslandık', 'Islandık, bu yüzden yağmur yağdı', 'Bu yüzden güzel', 'Yağmur sebeptir; ıslanmak bu yüzden ile anlatılan sonuçtur.'),
    ('orta', 'Aşağıdaki cümlelerden hangisinde dolayısıyla doğru kullanılmıştır?', 'Çok çalıştı, dolayısıyla başardı', 'Başardı, dolayısıyla çalıştı', 'Dolayısıyla mavi', 'Çalışmak sebeptir; başarmak dolayısıyla ile bağlanan sonuçtur.'),
    ('orta', 'Sebep-sonuç cümlesi hangisidir?', 'Susadığı için su içti', 'Su içti', 'Susadı', 'Susamak sebep, su içmek sonuçtur.'),
    ('orta', 'Sebep-sonuç cümlesi olmayan hangisidir?', 'Bahçede çiçek açtı', 'Yorulduğu için dinlendi', 'Aç olduğu için yemek yedi', 'Çiçek açmak basit bir olaydır; neden-sonuç yoktur.'),
    ('orta', 'Yukarıdaki ifadelerden hangisi yanlıştır?', 'III', 'I', 'II', 'Ama karşıtlık bildirir; sebep-sonuç kurmaz.', 'I. Sebep bir olayın nedenidir.\nII. Sonuç sebepten sonra gelir.\nIII. Ama sebep-sonuç kurar.'),
    ('orta', 'Yukarıdaki bağlaç bilgilerinden hangileri doğrudur?', 'Hepsi', 'Yalnız I', 'I ve II', 'Üç ifade de sebep-sonuç bağlaçları hakkında doğrudur.', 'I. İçin sebep-sonuç kurar.\nII. Bu yüzden sonuç bildirir.\nIII. Çünkü sebep bildirir.'),
    ('orta', 'Yukarıdaki cümlede bu yüzden şemsiye açtık. Parçada kaç sebep-sonuç ilişkisi vardır?', 'Bir', 'İki', 'Hiç', 'Yağmur yağması şemsiye açmaya neden olmuştur; bir ilişki vardır.', 'Yağmur yağdı.'),
    ('orta', 'Yukarıdaki cümlelerden hangisinde sebep-sonuç ilişkisi en açık kurulmuştur?', 'I ve II birlikte', 'Yalnız III', 'Hiçbiri', 'Yağmur yağması şemsiye açmaya neden olmuştur.', 'I. Yağmur yağdı.\nII. Şemsiye açtık.\nIII. Islanmadık.'),
    ('orta', 'Yukarıdaki olaylarda geç kalmak hangi olaya neden olmuştur?', 'Koşmak', 'Otobüse yetişmek', 'Uyumak', 'Geç kalmak koşmaya neden olmuştur.', 'I. Geç kaldı.\nII. Koştu.\nIII. Otobüse yetişti.'),
    ('orta', 'Yukarıdaki olaylarda sınavı kazanmanın sebebi hangisidir?', 'Çok çalışmak', 'Ailenin sevinmesi', 'Sınav', 'Sınavı kazanmanın sebebi çok çalışmaktır.', 'I. Çok çalıştı.\nII. Sınavı kazandı.\nIII. Ailesi sevindi.'),
    ('orta', 'Yukarıdaki olaylarda okula gitmemenin sebebi hangisidir?', 'Hasta olmak', 'Dinlenmek', 'Okul', 'Hasta olmak okula gitmemeye neden olmuştur.', 'I. Hasta oldu.\nII. Okula gitmedi.\nIII. Dinlendi.'),
    ('orta', 'Yukarıdaki olaylarda pencere kapanmasının sebebi hangisidir?', 'Rüzgarın esmesi', 'Odanın serinlemesi', 'Pencere', 'Rüzgar pencerenin kapanmasına neden olmuştur.', 'I. Rüzgar esti.\nII. Pencere kapandı.\nIII. Oda serindi.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Dikkatli yürümesi', 'Camın kırılması', 'Cam', 'Cam kırılması sebeptir; dikkatli yürümek sonuçtur.', 'Cam kırıldığı için dikkatli yürüdü.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok gürültü olması', 'Ders çalışamaması', 'Ders', 'Gürültü sebeptir; ders çalışamamak sonuçtur.', 'Çok gürültü olduğu için ders çalışamadı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Mutfağa gitmem', 'Karnımın acıkması', 'Mutfak', 'Acıkmak sebeptir; mutfağa gitmek sonuçtur.', 'Karnım acıktığı için mutfağa gittim.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Yolların buzlu olması', 'Yavaş yürümemiz', 'Yollar', 'Buzlu yollar sebeptir; yavaş yürümek sonuçtur.', 'Yollar buzlu olduğu için yavaş yürüdük.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Defterime yazmam', 'Öğretmenin anlatması', 'Defter', 'Öğretmenin anlatması sebeptir; deftere yazmak sonuçtur.', 'Öğretmen anlattığı için defterime yazdım.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Müziğin çok yüksek olması', 'Kulaklık takması', 'Müzik', 'Yüksek müzik sebeptir; kulaklık takmak sonuçtur.', 'Müzik çok yüksek olduğu için kulaklık taktı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Omzumun ağrıması', 'Çantanın ağır olması', 'Omuz', 'Ağır çanta sebeptir; omuz ağrısı sonuçtur.', 'Okul çantası ağır olduğu için omzum ağrıdı.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Sıcak olması', 'Fanı açması', 'Fan', 'Sıcak hava sebeptir; fan açmak sonuçtur.', 'Sıcak olduğu için fanı açtı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Yeni uç takması', 'Kalemin yazmaması', 'Uç', 'Kalemin yazmaması sebeptir; yeni uç takmak sonuçtur.', 'Kalem yazmadığı için yeni uç taktı.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Misafir geleceği', 'Evi temizlemesi', 'Ev', 'Misafir gelmesi sebeptir; evi temizlemek sonuçtur.', 'Misafir geleceği için evi temizledi.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Uzun düşünmesi', 'Sorunun zor olması', 'Soru', 'Zor soru sebeptir; uzun düşünmek sonuçtur.', 'Soru zor olduğu için uzun düşündü.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Rüzgarlı olması', 'Şapkasını tutması', 'Şapka', 'Rüzgar sebeptir; şapka tutmak sonuçtur.', 'Rüzgarlı olduğu için şapkasını tuttu.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Geç yatması', 'Çok oyun oynaması', 'Oyun', 'Çok oyun oynamak sebeptir; geç yatmak sonuçtur.', 'Çok oyun oynadığı için geç yattı.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Sınavın yaklaşması', 'Daha çok çalışması', 'Sınav', 'Sınavın yaklaşması sebeptir; daha çok çalışmak sonuçtur.', 'Sınav yaklaştığı için daha çok çalıştı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Üzgün olması', 'Kedisinin kaybolması', 'Kedi', 'Kedinin kaybolması sebeptir; üzülmek sonuçtur.', 'Kedisi kaybolduğu için üzgündü.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Hediye alması', 'Mutlu olması', 'Hediye', 'Hediye almak sebeptir; mutlu olmak sonuçtur.', 'Hediye aldığı için çok mutlu oldu.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Babasını araması', 'Yolda kalması', 'Baba', 'Yolda kalmak sebeptir; babayı aramak sonuçtur.', 'Yolda kaldığı için babasını aradı.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok konuşması', 'Susması istenmesi', 'Konuşma', 'Çok konuşmak sebeptir; susması istenmek sonuçtur.', 'Çok konuştuğu için susması istendi.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Sokak lambalarının yanması', 'Güneşin batması', 'Sokak', 'Güneşin batması sebeptir; lambaların yanması sonuçtur.', 'Güneş battığı için sokak lambaları yandı.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Kışın soğuk olması', 'Kalın mont giymesi', 'Mont', 'Soğuk kış sebeptir; kalın mont giymek sonuçtur.', 'Kışın soğuk olduğu için kalın mont giydi.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Kelime dağarcığının genişlemesi', 'Çok kitap okuması', 'Kitap', 'Kitap okumak sebeptir; kelime dağarcığının genişlemesi sonuçtur.', 'Çok kitap okuduğu için kelime dağarcığı genişledi.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Pilin bitmesi', 'Oyuncağın çalışmaması', 'Oyuncak', 'Pilin bitmesi sebeptir; oyuncağın çalışmaması sonuçtur.', 'Pil bittiği için oyuncak çalışmadı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Çiçeklerin solması', 'Sulama yapılmaması', 'Çiçek', 'Sulama yapmamak sebeptir; çiçeklerin solması sonuçtur.', 'Sulama yapılmadığı için çiçekler soldu.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok koşması', 'Nefesinin kesilmesi', 'Nefes', 'Çok koşmak sebeptir; nefesin kesilmesi sonuçtur.', 'Çok koştuğu için nefesi kesildi.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Sabah geç kalkması', 'Geç uyuması', 'Sabah', 'Geç uyumak sebeptir; geç kalkmak sonuçtur.', 'Geç uyuduğu için sabah geç kalktı.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Yağmur yağması', 'Bahçeye çıkmaması', 'Bahçe', 'Yağmur sebeptir; bahçeye çıkmamak sonuçtur.', 'Yağmur yağdığı için bahçeye çıkmadı.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Arkadaşından istemesi', 'Kalemi unutması', 'Arkadaş', 'Kalemi unutmak sebeptir; arkadaşından istemek sonuçtur.', 'Kalemi unuttuğu için arkadaşından istedi.'),
    ('orta', 'Yukarıdaki cümlede sebep hangisidir?', 'Çok gülmek', 'Karın ağrısı', 'Karın', 'Çok gülmek sebeptir; karın ağrısı sonuçtur.', 'Çok güldüğü için karın ağrısı oldu.'),
    ('orta', 'Yukarıdaki cümlede sonuç hangisidir?', 'Pencereyi kapatması', 'Fırtınanın çıkması', 'Pencere', 'Fırtına sebeptir; pencereyi kapatmak sonuçtur.', 'Fırtına çıktığı için pencereyi kapattı.'),
    ('orta', 'Sebep-sonuç ilişkisinde sonuç genellikle hangi bağlaçla bildirilir?', 'Bu yüzden', 'Ama', 'Veya', 'Bu yüzden bağlacı sebepten sonra gelen sonucu bildirir.'),
    # ── ZOR (50) ──
    ('zor', 'Yukarıdaki cümlelerin hangisinde sebep-sonuç ilişkisi yoktur?', 'III', 'I', 'II', 'III. cümlede tanım vardır; neden-sonuç kurulmamıştır.', 'I. Geç kaldığı için koştu.\nII. Aç olduğu için yemek yedi.\nIII. Koşmak spor yapmak demektir.'),
    ('zor', 'Yukarıdaki cümlelerin hangisinde sebep-sonuç sırası doğrudur?', 'I', 'II', 'III', 'I. cümlede önce sebep (çalışma), sonra sonuç (başarı) gelir.', 'I. Çalıştığı için başardı.\nII. Başardığı için çalıştı.\nIII. Başardı çünkü çalıştı.'),
    ('zor', 'Yukarıdaki cümlelerin hangisinde sebep-sonuç sırası yanlıştır?', 'II', 'I', 'III', 'II. cümlede başarı sebep gibi gösterilmiş; çalışmak sebep olmalıdır.', 'I. Yağmur yağınca ıslandı.\nII. Başardığı için çalıştı.\nIII. Hasta olduğu için yattı.'),
    ('zor', 'Yukarıdaki bağlaç tanımlarından hangileri doğrudur?', 'I ve II', 'Yalnız I', 'I, II ve III', 'I ve II doğru; dolayısıyla sonuç bildirir, sebep değil.', 'I. Çünkü kelimesi sebep bildirir.\nII. Bu yüzden kelimesi sonuç bildirir.\nIII. Dolayısıyla kelimesi sebep bildirir.'),
    ('zor', 'Yukarıdaki sebep-sonuç tanımlarından hangileri doğrudur?', 'I, II ve III', 'Yalnız II', 'I ve III', 'Üç ifade de doğru: sebep neden, sonuç sebebin ardından gelen durum, için bağlaç kurar.', 'I. Sebep bir olayın nedenidir.\nII. Sonuç sebepten sonra ortaya çıkar.\nIII. İçin bağlacı sebep-sonuç kurar.'),
    ('zor', 'Yukarıdaki sebep örneklerinden hangisi yanlıştır?', 'Yalnız III', 'I ve II', 'I, II ve III', 'III yanlış: başarı çalışmanın sonucudur, sebebi değil.', 'I. Yağmur yağmak ıslanmanın sebebidir.\nII. Geç kalmak otobüsü kaçırmanın sebebidir.\nIII. Başarı çalışmanın sebebidir.'),
    ('zor', 'Yukarıdaki eşleştirmelerden hangileri doğrudur?', 'II ve III', 'Yalnız I', 'I ve II', 'II ve III doğru: hasta-dinlenme ve yağmur-şemsiye. I ters kurulmuştur.', 'I. Sebep: ıslanmak — Sonuç: yağmur\nII. Sebep: hasta olmak — Sonuç: dinlenmek\nIII. Sebep: yağmur — Sonuç: şemsiye açmak'),
    ('zor', 'Yukarıdaki eşleştirmelerden hangileri yanlıştır?', 'I ve III', 'Yalnız II', 'II ve III', 'I ve III yanlış: karanlık sonuçtur, başarı sonuçtur. II doğrudur.', 'I. Sebep: karanlık — Sonuç: elektrik kesintisi\nII. Sebep: çalışmak — Sonuç: başarı\nIII. Sebep: başarı — Sonuç: çalışmak'),
    ('zor', 'Yukarıdaki parçada kaç sebep-sonuç ilişkisi vardır?', 'İki', 'Bir', 'Üç', 'Parçada yağmur-ıslanma ve geç kalma-otobüs kaçırma olmak üzere iki ilişki vardır.', 'Yağmur yağınca ıslandık. Sonra geç kaldığımız için otobüsü kaçırdık.'),
    ('zor', 'Yukarıdaki parçada ilk sebep-sonuç ilişkisinin sebebi hangisidir?', 'Yağmur yağması', 'Islanmak', 'Otobüsü kaçırmak', 'İlk ilişkide yağmur yağması ıslanmanın sebebidir.', 'Yağmur yağınca ıslandık. Sonra geç kaldığımız için otobüsü kaçırdık.'),
    ('zor', 'Yukarıdaki parçada ikinci sebep-sonuç ilişkisinin sonucu hangisidir?', 'Otobüsü kaçırmak', 'Yağmur yağmak', 'Islanmak', 'İkinci ilişkide geç kalmak sebep, otobüsü kaçırmak sonuçtur.', 'Yağmur yağınca ıslandık. Sonra geç kaldığımız için otobüsü kaçırdık.'),
    ('zor', 'Yukarıdaki parçada sebep-sonuç ilişkisi hangi cümlede vardır?', 'II', 'I', 'III', 'II. cümlede çalışmak sebep, kazanmak sonuçtur.', 'I. Bugün hava güzel.\nII. Çok çalıştığı için sınavı kazandı.\nIII. Sınav zordu.'),
    ('zor', 'Hangi seçenekte sebep, sonuç ve bağlaç doğru kullanılmıştır?', 'Hasta olduğu için okula gitmedi', 'Okula gitmediği için hasta oldu', 'Hasta oldu, bu yüzden okula gitti', 'Hasta olmak gitmemenin nedenidir; için bağlacı doğru kullanılmıştır.'),
    ('zor', 'Hangi seçenekte sebep-sonuç ilişkisi yanlış kurulmuştur?', 'Başarılı olduğu için çok çalıştı', 'Çok çalıştığı için başarılı oldu', 'Hasta olduğu için dinlendi', 'Başarılı olmak çalışmanın sonucudur; ters kurulmuştur.'),
    ('zor', 'Hangi seçenekte bu yüzden doğru kullanılmıştır?', 'Elektrik kesildi, bu yüzden ders çalışamadık', 'Ders çalışamadık, bu yüzden elektrik kesildi', 'Bu yüzden güzel', 'Elektriğin kesilmesi sebeptir; ders çalışamamak sonuçtur.'),
    ('zor', 'Yukarıdaki cümlede sonuç hangisidir?', 'Ağacın devrilmesi', 'Fırtınanın çıkması', 'Ağaç', 'Fırtına sebeptir; ağacın devrilmesi sonuçtur.', 'Fırtına çıktığı için ağaç devrildi.'),
    ('zor', 'Yukarıdaki cümlede sebep hangisidir?', 'Gece geç yatmak', 'Sabah geç kalkmak', 'Sabah', 'Geç yatmak nedendir; geç kalkmak sonuçtur.', 'Gece geç yattığı için sabah geç kalktı.'),
    ('zor', 'Yukarıdaki cümlede sebep hangisidir?', 'Hasta olmak', 'Okula gitmemek', 'Okul', 'Bu cümlede çünkü kelimesinden sonra gelen hasta olmak sebebi gösterir.', 'Okula gitmedi çünkü hasta oldu.'),
    ('zor', 'Yukarıdaki cümlede sonuç hangisidir?', 'Sesinin kısılması', 'Bağırmak', 'Ses', 'Bağırmak sebeptir; sesin kısılması dolayısıyla ile bağlanan sonuçtur.', 'Çok bağırdı, dolayısıyla sesi kısıldı.'),
    ('zor', 'Aşağıdaki cümlelerden hangisinde sebep-sonuç en iyi açıklanmıştır?', 'Okula gitmedi çünkü hasta oldu; hasta olmak gitmemesinin nedenidir', 'Okula gitmedi', 'Hasta oldu', 'İlk cümlede hem sonuç hem sebep açıkça belirtilmiştir.'),
    ('zor', 'Yukarıdaki cümlelerden hangisinde fırtına ile ağaç devrilmesi arasında sebep-sonuç vardır?', 'II', 'I', 'III', 'II. cümlede fırtına sebep, ağacın devrilmesi sonuçtur.', 'I. Ağaç uzun.\nII. Fırtına çıktığı için ağaç devrildi.\nIII. Fırtına doğa olayıdır.'),
    ('zor', 'Yukarıdaki parçada birinci sebep-sonuç ilişkisinin sonucu hangisidir?', 'Islanmak', 'Yağmur yağmak', 'Otobüs kaçırmak', 'Yağmur yağması ıslanmanın sebebidir; ıslanmak sonuçtur.', 'Yağmur yağınca ıslandık. Geç kaldığımız için otobüsü kaçırdık.'),
    ('zor', 'Yukarıdaki parçada ikinci sebep-sonuç ilişkisinin sebebi hangisidir?', 'Geç kalmak', 'Otobüsü kaçırmak', 'Islanmak', 'Geç kalmak otobüsü kaçırmanın sebebidir.', 'Yağmur yağınca ıslandık. Geç kaldığımız için otobüsü kaçırdık.'),
    ('zor', 'Hangi cümlede sebep-sonuç ters kurulmuştur?', 'Başardığı için çalıştı', 'Çalıştığı için başardı', 'Hasta olduğu için yattı', 'Başarmak çalışmanın sonucudur; sebep gibi gösterilmesi yanlıştır.'),
    ('zor', 'Okula gitmeme gerekçesini sebep olarak gösteren cümle hangisidir?', 'Okula gitmedi çünkü hasta oldu', 'Çünkü okula gitmedi hasta oldu', 'Hasta çünkü oldu', 'Hasta olmak gitmemenin nedenidir; çünkü doğru kullanılmıştır.'),
    ('zor', 'Hangi cümlede dolayısıyla kelimesi yanlış kullanılmıştır?', 'Güzel dolayısıyla hava', 'Çalıştı, dolayısıyla başardı', 'Yağmur yağdı, dolayısıyla ıslandık', 'Güzel dolayısıyla hava anlamsızdır; sebep-sonuç kurulmamıştır.'),
    ('zor', 'Sebep-sonuç cümlesinde için bağlacı hangi bölümde kullanılır?', 'Sebep bölümünün sonunda', 'Sonuç bölümünün sonunda', 'Cümlenin başında', 'İçin bağlacı sebep bölümünün sonunda kullanılır.'),
    ('zor', 'Bu yüzden bağlacı hangi bölümden önce gelir?', 'Sonuç bölümünden önce', 'Sebep bölümünden önce', 'Cümlenin sonunda', 'Bu yüzden sonuç bölümünden önce gelir ve sonucu bildirir.'),
    ('zor', 'Aşağıdakilerden hangisi sebep-sonuç cümlesi değildir?', 'Bugün pazartesi', 'Yağmur yağdığı için ıslandık', 'Aç olduğu için yemek yedi', 'Bugün pazartesi basit bir bilgidir; sebep-sonuç yoktur.'),
    ('zor', 'Aşağıdakilerden hangisi sebep-sonuç cümlesidir?', 'Soğuk olduğu için mont giydi', 'Mont mavi', 'Soğuk hava', 'Soğuk olmak mont giymenin nedenidir.'),
    ('zor', 'Yukarıdaki sebep-sonuç kurallarından hangileri doğrudur?', 'I ve II', 'Yalnız III', 'I, II ve III', 'I ve II doğru; ama karşıtlık bildirir.', 'I. Sebep her zaman sonuçtan önce gelir.\nII. Sonuç sebebin ardından ortaya çıkar.\nIII. Ama sebep-sonuç kurar.'),
    ('zor', 'Yukarıdaki bağlaç ifadelerinden hangisi yanlıştır?', 'III', 'I', 'II', 'Çünkü sebep bildirir, sonuç değil.', 'I. İçin sebep-sonuç kurar.\nII. Bu yüzden sonuç bildirir.\nIII. Çünkü sonuç bildirir.'),
    ('zor', 'Yukarıdaki sebep-sonuç örneklerinden hangileri doğrudur?', 'Hepsi', 'Yalnız I', 'I ve III', 'Üç ifade de doğru sebep-sonuç eşleştirmesidir.', 'I. Yağmur yağmak ıslanmanın sebebidir.\nII. Çalışmak başarının sebebidir.\nIII. Geç kalmak otobüsü kaçırmanın sebebidir.'),
    ('zor', 'Yukarıdaki ters eşleştirmelerden hangileri yanlıştır?', 'I ve III', 'Yalnız II', 'II ve III', 'I ve III yanlış: karanlık sonuçtur, başarı sonuçtur.', 'I. Sebep: karanlık — Sonuç: elektrik kesintisi\nII. Sebep: yağmur — Sonuç: ıslanmak\nIII. Sebep: başarı — Sonuç: çalışmak'),
    ('zor', 'Yukarıdaki parçada toplam kaç sebep-sonuç ilişkisi vardır?', 'Üç', 'Bir', 'İki', 'Parçada hasta-dinlenme, yağmur-ıslanma ve geç kalma-otobüs kaçırma olmak üzere üç ilişki vardır.', 'Hasta olduğu için dinlendi. Yağmur yağınca ıslandı. Geç kaldığı için otobüsü kaçırdı.'),
    ('zor', 'Yukarıdaki parçada yağmur yağması hangi sonuca neden olmuştur?', 'Islanmak', 'Dinlenmek', 'Otobüs kaçırmak', 'Yağmur yağması ıslanmaya neden olmuştur.', 'Hasta olduğu için dinlendi. Yağmur yağınca ıslandı. Geç kaldığı için otobüsü kaçırdı.'),
    ('zor', 'Yukarıdaki parçada hasta olma hangi sonuca neden olmuştur?', 'Dinlenmek', 'Islanmak', 'Otobüs kaçırmak', 'Hasta olmak dinlenmeye neden olmuştur.', 'Hasta olduğu için dinlendi. Yağmur yağınca ıslandı. Geç kaldığı için otobüsü kaçırdı.'),
    ('zor', 'Hangi seçenekte sebep-sonuç ilişkisi doğru kurulmuştur?', 'Çok çalıştığı için sınavı kazandı', 'Sınavı kazandığı için çok çalıştı', 'Sınavı kazandı çünkü başarılı', 'Çalışmak sebeptir; sınavı kazanmak sonuçtur.'),
    ('zor', 'Hangi seçenekte için bağlacı yanlış kullanılmıştır?', 'Gittiği için okula hasta oldu', 'Hasta olduğu için okula gitmedi', 'Aç olduğu için yemek yedi', 'Okula gitmek hastalığın sebebi olamaz; ters kurulmuştur.'),
    ('zor', 'Sebep-sonuç ilişkisinde hangi bağlaç sebebi bildirir?', 'Çünkü', 'Bu yüzden', 'Dolayısıyla', 'Çünkü kelimesi sebebi bildirir.'),
    ('zor', 'Sebep-sonuç ilişkisinde hangi bağlaç sonucu bildirir?', 'Bu yüzden', 'Çünkü', 'Ve', 'Bu yüzden kelimesi sonucu bildirir.'),
    ('zor', 'Aşağıdakilerden hangisi sebep-sonuç cümlesi olarak yanlıştır?', 'Başarılı olduğu için çalıştı', 'Hasta olduğu için dinlendi', 'Yağmur yağdığı için ıslandı', 'Başarılı olmak çalışmanın sonucudur; sebep gibi gösterilmesi yanlıştır.'),
    ('zor', 'Aşağıdakilerden hangisi sebep-sonuç cümlesi olarak doğrudur?', 'Geç kaldığı için otobüsü kaçırdı', 'Otobüsü kaçırdığı için geç kaldı', 'Geç kaldı çünkü otobüs', 'Geç kalmak otobüsü kaçırmanın nedenidir.'),
    ('zor', 'Yukarıdaki cümlelerden hangisinde yağmur ile ıslanma arasında sebep-sonuç vardır?', 'I', 'II', 'III', 'I. cümlede yağmur sebep, ıslanma sonuçtur.', 'I. Yağmur yağınca ıslandı.\nII. Bugün hava güzel.\nIII. Ali okula gitti.'),
    ('zor', 'Yukarıdaki cümlelerden hangisinde sebep-sonuç kurulmamıştır?', 'II', 'I', 'III', 'II. cümlede basit bilgi vardır; sebep-sonuç kurulmamıştır.', 'I. Yorulduğu için dinlendi.\nII. Bugün cuma.\nIII. Aç olduğu için yemek yedi.'),
    ('zor', 'Sebep-sonuç ilişkisini en iyi açıklayan ifade hangisidir?', 'Sebep bir olayın nedenidir, sonuç sebebin ardından gelir', 'Sebep ve sonuç aynı şeydir', 'Sonuç her zaman önce gelir', 'Sebep neden, sonuç sebebin ardından ortaya çıkan durumdur.'),
    ('zor', 'Aşağıdakilerden hangisi sebep-sonuç konusunda yanlıştır?', 'Sonuç sebepten önce gelir', 'İçin bağlacı sebep-sonuç kurar', 'Bu yüzden sonuç bildirir', 'Sonuç sebepten sonra gelir; önce gelmesi yanlıştır.'),
    ('zor', 'Hangi cümlede sebep ve sonuç doğru eşleştirilmiştir?', 'Elektrik kesildi, bu yüzden lamba söndü', 'Lamba söndü, bu yüzden elektrik kesildi', 'Bu yüzden lamba söndü elektrik', 'Elektriğin kesilmesi lambanın sönmesine neden olur.'),
    ('zor', 'Hangi cümlede sebep-sonuç ilişkisi kurulmamıştır?', 'Bahçede kırmızı gül var', 'Susadığı için su içti', 'Yorulduğu için dinlendi', 'Gülün rengini anlatmak sebep-sonuç değildir.'),
    ('zor', 'Sebep-sonuç cümlelerinde en sık kullanılan bağlaç hangisidir?', 'İçin', 'Ama', 'Veya', 'İçin bağlacı sebep-sonuç cümlelerinde en sık kullanılır.'),
]

def get_questions() -> list[dict]:
    out = []
    for i, row in enumerate(_RAW, start=1):
        level, text, correct, w1, w2, exp = row[:6]
        premise = row[6] if len(row) > 6 else None
        out.append({
            "id": f"cumle3_{i:03d}",
            "level": level,
            "premise": premise,
            "text": text,
            "correct": correct,
            "wrong1": w1,
            "wrong2": w2,
            "explanation": exp,
        })
    return out
