# -*- coding: utf-8 -*-
"""3. sınıf Olay Sırası ve Hikâye Unsurları — 150 soru."""
from __future__ import annotations

_RAW: list[tuple] = [
    # ── KOLAY (50) ──
    ('kolay', 'Hikâyede olayları yaşayan kişiye ne ad verilir?', 'Kahraman', 'Yer', 'Zaman', 'Kahraman, hikâyede olayları yapan veya yaşayan kişidir.'),
    ('kolay', 'Olayın geçtiği yere ne ad verilir?', 'Yer unsuru', 'Kahraman', 'Olay unsuru', 'Yer unsuru, hikâyedeki olayların geçtiği mekândır.'),
    ('kolay', 'Olayın hangi gün veya saatte olduğunu anlatan unsura ne denir?', 'Zaman unsuru', 'Yer unsuru', 'Kahraman', 'Zaman unsuru, olayın ne zaman gerçekleştiğini söyler.'),
    ('kolay', 'Hikâyede yaşanan işe ne ad verilir?', 'Olay unsuru', 'Kahraman', 'Başlık', 'Olay unsuru, hikâyede anlatılan ve yaşanan iştir.'),
    ('kolay', 'Kim sorusu hangi hikâye unsurunu buldurur?', 'Kahraman', 'Yer', 'Zaman', 'Kim sorusu olayları yaşayan kişiyi, yani kahramanı buldurur.'),
    ('kolay', 'Nerede sorusu hangi hikâye unsurunu buldurur?', 'Yer', 'Kahraman', 'Olay', 'Nerede sorusu olayın geçtiği yeri gösterir.'),
    ('kolay', 'Ne zaman sorusu hangi hikâye unsurunu buldurur?', 'Zaman', 'Yer', 'Kahraman', 'Ne zaman sorusu olayın hangi gün veya saatte olduğunu verir.'),
    ('kolay', 'Ne oldu sorusu hangi hikâye unsurunu buldurur?', 'Olay', 'Kahraman', 'Yer', 'Ne oldu sorusu hikâyede yaşanan işi buldurur.'),
    ('kolay', 'Hikâyenin dört temel unsuru hangi seçenekte doğru verilmiştir?', 'Kahraman, yer, zaman, olay', 'Dize, kıta, mısra, şair', 'Başlık, sayfa, harf, cümle', 'Hikâyede kahraman, yer, zaman ve olay unsurları bulunur.'),
    ('kolay', 'Olayları oluş sırasına göre anlatmak neden önemlidir?', 'Hikâyenin anlaşılması için', 'Kitabın kalın olması için', 'Resim çizmek için', 'Doğru sırada anlatılan hikâye kolayca anlaşılır.'),
    ('kolay', 'Önce sözcüğü hangi olayı gösterir?', 'İlk gelen olayı', 'En son gelen olayı', 'Hiç olmayan olayı', 'Önce kelimesi diğerlerinden önce gerçekleşen ilk olayı belirtir.'),
    ('kolay', 'Sonra sözcüğü hangi olayı gösterir?', 'Daha sonra gelen olayı', 'En baştaki olayı', 'Olmayan olayı', 'Sonra kelimesi bir olaydan sonra gelen sonraki olayı gösterir.'),
    ('kolay', 'En baştaki olaya genellikle hangi sıra numarası verilir?', '1', '3', '5', 'Olayların oluş sırasında ilk olana 1 numarası verilir.'),
    ('kolay', 'Sıradaki ikinci olaya hangi numara verilir?', '2', '1', '4', 'İkinci olaya 2 numarası verilir; böylece sıra belli olur.'),
    ('kolay', 'Aşağıdakilerden hangisi hikâye unsuru değildir?', 'Dize', 'Kahraman', 'Yer', 'Dize şiirin satırıdır; kahraman ve yer hikâye unsurudur.'),
    ('kolay', 'Yukarıdaki cümlede kahramanı söyleyin.', 'Elif', 'Sabah', 'Uyandı', "Uyuyan kişi Elif'tir; kahraman Elif'tir.", 'Elif sabah erkenden uyandı.'),
    ('kolay', 'Yukarıdaki cümledeolayların geçtiği yer neresidir?', 'Park', 'Top', 'Biz', 'Parkta sözcüğü olayın parkta geçtiğini söyler.', 'Parkta top oynadık.'),
    ('kolay', 'Yukarıdaki cümledezaman unsuru hangisidir?', 'Akşam', 'Güneş', 'Sokak lambaları', 'Akşam sözcüğü olayın hangi vakitte olduğunu anlatır.', 'Akşam olunca sokak lambaları yandı.'),
    ('kolay', 'Yukarıdaki cümledeyaşanan olay nedir?', 'Köpeğin havlayarak koşması', 'Köpek', 'Bahçe', 'Köpeğin havlayarak koşması hikâyede yaşanan olaydır.', 'Köpek havlayarak bahçeye koştu.'),
    ('kolay', 'Yukarıdaki cümledeolayları yapan kişi kimdir?', 'Mert', 'Anne', 'Çay', "Çay getiren kişi Mert'tir; kahraman Mert'tir.", 'Mert annesine çay getirdi.'),
    ('kolay', 'Yukarıdaki cümledeyer unsuru hangisidir?', 'Deniz kenarı', 'Kum', 'Kale', 'Deniz kenarında ifadesi olayın geçtiği yeri gösterir.', 'Deniz kenarında kumdan kale yaptılar.'),
    ('kolay', 'Yukarıdaki cümledeolay ne zamandır?', 'Öğle arası', 'Kantin', 'Simit', 'Öğle arası olayın ne zaman olduğunu söyler.', 'Öğle arasında kantinden simit aldı.'),
    ('kolay', 'Yukarıdaki cümledeanlatılan iş hangisidir?', 'Pencereyi kapatmak', 'Yağmur', 'Pencere', 'Pencereyi kapatmak hikâyede yaşanan iştir.', 'Yağmur başlayınca pencereyi kapattı.'),
    ('kolay', 'Yukarıdaki cümledehikâye kahramanı kimdir?', 'Sude', 'Kütüphane', 'Kitap', "Kitap seçen kişi Sude'dur; kahraman Sude'dur.", 'Sude kütüphaneden kitap seçti.'),
    ('kolay', 'Yukarıdaki cümledezaman unsuru hangisidir?', 'Pazar günü', 'Piknik', 'Gittik', 'Pazar günü olayın ne zaman olduğunu verir.', 'Pazar günü pikniğe gittik.'),
    ('kolay', 'Yukarıdaki cümledekim hakkında anlatım yapılmıştır?', 'Can', 'Sabah', 'Park', "Parka giden kişi Can'dır; kahraman Can'dır.", 'Can sabah parka gitti.'),
    ('kolay', 'Yukarıdaki cümledeolay nerede geçmiştir?', 'Okul', 'Sınav', 'Oldu', 'Okulda sözcüğü olayın okulda geçtiğini belirtir.', 'Okulda sınav oldu.'),
    ('kolay', 'Yukarıdaki cümledeolay hangi saatte olmuştur?', 'Gece yarısı', 'Fırtına', 'Çıktı', 'Gece yarısı olayın hangi saatte olduğunu anlatır.', 'Gece yarısı fırtına çıktı.'),
    ('kolay', 'Yukarıdaki cümledeyaşanan olay nedir?', 'Pastayı fırına koymak', 'Fatma', 'Pasta', "Fatma'nın pastayı fırına koyması anlatılan iştir.", 'Fatma pastayı fırına koydu.'),
    ('kolay', 'Yukarıdaki cümledeyer unsuru neresidir?', 'Bahçe', 'Çiçek', 'Açmak', 'Bahçede sözcüğü olayın bahçede geçtiğini gösterir.', 'Bahçede çiçekler açtı.'),
    ('kolay', 'Önce dişlerini fırçaladı. Sonra okula gitti. İlk gerçekleşen olay hangisidir?', 'Dişlerini fırçalamak', 'Okula gitmek', 'Uyumak', 'Önce kelimesi diş fırçalamanın ilk geldiğini söyler.'),
    ('kolay', 'Önce ödevini yaptı. Sonra televizyon izledi. Sonra gerçekleşen olay hangisidir?', 'Televizyon izlemek', 'Ödev yapmak', 'Uyumak', 'Sonra kelimesi televizyon izlemenin ödevden sonra geldiğini gösterir.'),
    ('kolay', 'Yukarıdaki cümlelerde önce gerçekleşen olay hangisidir?', 'Kapı çaldı', 'Misafiri karşıladı', 'Yemek yedi', '1 numaralı olay ilk sıradadır; kapı çalmadan misafir karşılanamaz.', '1) Kapı çaldı. 2) Misafiri karşıladı.'),
    ('kolay', 'Yukarıdaki olaylar arasında sonraki olay hangisidir?', 'Sofrayı kurmak', 'Yemek pişirmek', 'Televizyon izlemek', '2 numaralı olay ikinci sıradadır; önce yemek pişer, sonra sofra kurulur.', '1) Yemek pişti. 2) Sofrayı kurdu.'),
    ('kolay', 'Aşağıdakilerden hangisi yer unsuruna örnektir?', 'Orman', 'Ayşe', 'Sabah', 'Orman bir mekândır; Ayşe kahraman, sabah zaman unsurudur.'),
    ('kolay', 'Aşağıdakilerden hangisi zaman unsuruna örnektir?', 'Cumartesi sabahı', 'Mehmet', 'Sınıf', 'Cumartesi sabahı bir zaman bilgisidir; Mehmet kahraman, sınıf yer unsurudur.'),
    ('kolay', 'Aşağıdakilerden hangisi kahraman olabilir?', 'Öğrenci', 'Kütüphane', 'Kış', 'Öğrenci bir kişidir ve hikâyede kahraman olabilir.'),
    ('kolay', 'Aşağıdakilerden hangisi olaydır?', 'Kitap okumak', 'Deniz', 'Salı', 'Kitap okumak yapılan bir iştir; deniz yer, salı zaman olabilir.'),
    ('kolay', 'Hikâyede olaylar hangi sırayla anlatılmalıdır?', 'Oluş sırasına göre', 'Rastgele', 'Tersten', 'Olaylar gerçekte oldukları sırayla anlatılırsa hikâye anlaşılır.'),
    ('kolay', 'Olayları karışık anlatırsak ne olur?', 'Hikâye anlaşılmaz', 'Hikâye daha güzel olur', 'Hikâye kısalır', 'Sıra karışırsa dinleyen hangi olayın önce olduğunu bilemez.'),
    ('kolay', 'Sıra numarası vermek ne işe yarar?', 'Olay sırasını göstermek', 'Kitabı uzatmak', 'Resim çizmek', '1, 2, 3 gibi numaralar olayların hangi sırayla olduğunu gösterir.'),
    ('kolay', 'Hikâyede en son olan olaya genellikle hangi numara verilir?', 'En büyük numara', '1', '0', 'Son olay listede en büyük sıra numarasını alır.'),
    ('kolay', 'En son kelimesi hangi olayı gösterir?', 'Sondaki olayı', 'İlk olayı', 'Ortadaki olayı', 'En son sözcüğü olayların en sonuncusunu belirtir.'),
    ('kolay', 'Ardından kelimesi ne anlama gelir?', 'Hemen sonra', 'Çok önce', 'Hiç olmaz', 'Ardından bir olayın hemen ardından gelen olayı gösterir.'),
    ('kolay', 'Daha önce kelimesi ne anlama gelir?', 'Daha önceki bir zamanda', 'Şimdi', 'Hiçbir zaman', 'Daha önce geçmişte olan bir olayı anlatır.'),
    ('kolay', 'Hikâye unsurlarından biri olan kahraman neyi anlatır?', 'Olayları yaşayan kişiyi', 'Olayın geçtiği yeri', 'Olayın saatini', 'Kahraman hikâyede olayları yapan veya yaşayan kişidir.'),
    ('kolay', 'Hikâye unsurlarından biri olan yer neyi anlatır?', 'Olayın geçtiği mekânı', 'Olayı yapan kişiyi', 'Olayın saatini', 'Yer unsuru olayın hangi mekânda geçtiğini söyler.'),
    ('kolay', 'Hikâye unsurlarından biri olan zaman neyi anlatır?', 'Olayın geçtiği gün veya saati', 'Olayı yapan kişiyi', 'Olayın adını', 'Zaman unsuru olayın ne zaman olduğunu bildirir.'),
    ('kolay', 'Hikâye unsurlarından biri olan olay neyi anlatır?', 'Yaşanan işi veya durumu', 'Kitabın kapağını', 'Yazarın adını', 'Olay unsuru hikâyede yaşanan işleri anlatır.'),
    ('kolay', 'Olay sırasını doğru vermek dinleyiciye ne sağlar?', 'Hikâyeyi kolay anlamasını', 'Kitabı uzatmasını', 'Resim çizmesini', 'Doğru sıra sayesinde olaylar birbirine bağlanır ve hikâye anlaşılır.'),
    # ── ORTA (50) ──
    ('orta', 'Yukarıdaki metinde olayları yaşayan kişi kimdir?', 'Defne', 'Okul', 'Sabah erkenden', "Defne hikâyede olayları yaşayan kişidir; kahraman Defne'dir.", 'Defne sabah erkenden kalktı. Kahvaltısını yaptıktan sonra okula gitti.'),
    ('orta', 'Yukarıdaki metinde olay nerede geçmektedir?', 'Okul', 'Defne', 'Kahvaltı', 'Defne okula gitmiştir; olayın geçtiği yer okuldur.', 'Defne sabah erkenden kalktı. Kahvaltısını yaptıktan sonra okula gitti.'),
    ('orta', "Yukarıdaki metinde Defne'nin günü hangi vakitte başlamıştır?", 'Sabah erkenden', 'Defne', 'Okul', 'Sabah erkenden ifadesi olayın ne zaman başladığını anlatır.', 'Defne sabah erkenden kalktı. Kahvaltısını yaptıktan sonra okula gitti.'),
    ('orta', 'Yukarıdaki metinde anlatılan olaylardan biri hangisidir?', 'Okula gitmek', 'Defne', 'Sabah', 'Kahvaltıdan sonra okula gitmek hikâyede yaşanan olaydır.', 'Defne sabah erkenden kalktı. Kahvaltısını yaptıktan sonra okula gitti.'),
    ('orta', 'Yukarıdaki metinde kahvaltı ile okula gitme arasındaki ilişki nasıldır?', 'Önce kahvaltı, sonra okula gitme', 'Önce okula gitme, sonra kahvaltı', 'İkisi aynı anda', 'Önce kahvaltı yapılmış, sonra okula gidilmiştir.', 'Defne sabah erkenden kalktı. Kahvaltısını yaptıktan sonra okula gitti.'),
    ('orta', 'Yukarıdaki metinde hikâyenin kahramanı kimdir?', 'Ailemiz / biz', 'Park', 'Cumartesi', 'Hikâyede olayları yaşayan kişiler ailemizdir.', 'Cumartesi günü ailemizle parka gittik. Orada bisiklete bindik ve dondurma yedik.'),
    ('orta', 'Yukarıdaki metinde bisiklete binme olayı hangi mekânda geçmiştir?', 'Park', 'Bisiklet', 'Dondurma', 'Park olayın geçtiği yerdir.', 'Cumartesi günü ailemizle parka gittik. Orada bisiklete bindik ve dondurma yedik.'),
    ('orta', 'Yukarıdaki metinde olay hangi gün geçmiştir?', 'Cumartesi günü', 'Pazar', 'Pazartesi', 'Cumartesi günü zaman unsurudur.', 'Cumartesi günü ailemizle parka gittik. Orada bisiklete bindik ve dondurma yedik.'),
    ('orta', 'Yukarıdaki metinde bisiklete binmek hangi unsurdur?', 'Olay', 'Kahraman', 'Zaman', 'Bisiklete binmek hikâyede yaşanan olaydır.', 'Cumartesi günü ailemizle parka gittik. Orada bisiklete bindik ve dondurma yedik.'),
    ('orta', 'Yukarıdaki metinde parka gitmeden önce ne belirtilmiştir?', 'Cumartesi günü', 'Dondurma yemek', 'Uyumak', 'Metin cumartesi günü parka gidildiğini söyler.', 'Cumartesi günü ailemizle parka gittik. Orada bisiklete bindik ve dondurma yedik.'),
    ('orta', 'Yukarıdaki metinde masalı anlatan kişi kimdir?', 'Dedem', 'Masal', 'Göz', 'Masalı anlatan kişi dedemdir.', 'Kış akşamı dedem bize masal anlattı. Dinlerken gözlerimiz yavaş yavaş kapandı.'),
    ('orta', 'Yukarıdaki metinde olay hangi mevsim akşamında geçmiştir?', 'Kış akşamı', 'Yaz sabahı', 'İlkbahar öğleden sonra', 'Kış akşamı zaman unsurudur.', 'Kış akşamı dedem bize masal anlattı. Dinlerken gözlerimiz yavaş yavaş kapandı.'),
    ('orta', 'Yukarıdaki metinde yaşanan olay hangisidir?', 'Masal anlatmak', 'Dedem', 'Kış', 'Masal anlatmak hikâyede yaşanan olaydır.', 'Kış akşamı dedem bize masal anlattı. Dinlerken gözlerimiz yavaş yavaş kapandı.'),
    ('orta', 'Yukarıdaki metinde gözlerin kapanması neyi gösterir?', 'Masal dinlerken uykunun gelmesi', 'Kahramanın adını', 'Yer unsurunu', 'Gözlerin kapanması masal dinlerken uykunun geldiğini anlatır.', 'Kış akşamı dedem bize masal anlattı. Dinlerken gözlerimiz yavaş yavaş kapandı.'),
    ('orta', 'Yukarıdaki metinde masal anlatma olayı nerede geçmiştir?', 'Ev', 'Dedem', 'Masal', 'Masal anlatma olayı evde geçmiştir.', 'Kış akşamı dedem bize masal anlattı. Dinlerken gözlerimiz yavaş yavaş kapandı.'),
    ('orta', 'Önce yağmur yağdı. Sonra gökkuşağı belirdi. İlk olay hangisidir?', 'Yağmur yağması', 'Gökkuşağı belirmesi', 'Güneş batması', 'Önce yağmur yağmış; gökkuşağı ondan sonra belirmiştir.'),
    ('orta', 'Önce fırını ısıttı. Sonra ekmeği pişirdi. Sonraki olay hangisidir?', 'Ekmeği pişirmek', 'Fırını ısıtmak', 'Marketten ekmek almak', 'Fırın ısındıktan sonra ekmek pişirilmiştir.'),
    ('orta', 'Yukarıdaki numaralı olaylardan ilk sıradaki hangisidir?', 'Kamp alanına varmak', 'Çanta hazırlamak', 'Otobüse binmek', '3 numaralı olay en son gerçekleşen olaydır.', '1) Çantasını hazırladı. 2) Otobüse bindi.'),
    ('orta', 'Yukarıdaki cümlelerde en son gerçekleşen olay hangisidir?', 'Sulamak', 'Tohum ekmek', 'Filiz çıkması', '2 numaralı olay sulamaktır.', '1) Tohum ekti. 2) Suladı.'),
    ('orta', 'Önce kitabı okudu. Daha sonra özet çıkardı. Özet çıkarmadan önce ne yapmıştır?', 'Kitabı okumuş', 'Televizyon izlemiş', 'Uyumuş', 'Özet çıkarmadan önce kitabı okumuştur.'),
    ('orta', 'Önce pazar alışverişi yaptı. Ardından yemek pişirdi. Yemek pişirmeden önce ne olmuştur?', 'Alışveriş yapılmış', 'Misafir gelmiş', 'Telefon çalmış', 'Ardından kelimesi alışverişten sonra yemek pişirildiğini gösterir.'),
    ('orta', 'Hikâyede yer unsuru aşağıdakilerden hangisi olabilir?', 'Market', 'Ali', 'Dün', 'Market bir mekândır; Ali kahraman, dün zaman olabilir.'),
    ('orta', 'Hikâyede zaman unsuru aşağıdakilerden hangisi olabilir?', 'Gece yarısı', 'Park', 'Kedi', 'Gece yarısı bir zaman bilgisidir.'),
    ('orta', 'Hikâyede olay unsuru aşağıdakilerden hangisi olabilir?', 'Resim yapmak', 'Sınıf', 'Perşembe', 'Resim yapmak bir iştir; sınıf yer, perşembe zaman olabilir.'),
    ('orta', 'Olay sırasını bozarsak dinleyici neyi anlayamaz?', 'Hangi olayın önce olduğunu', 'Kahramanın adını', 'Kitabın rengini', 'Sıra karışırsa önce-sonra ilişkisi kaybolur.'),
    ('orta', 'Yukarıdaki metinde en son gerçekleşen olay hangisidir?', 'Okula yürümek', 'Ayakkabı giymek', 'Ceket almak', 'En son okula yürümüştür; bu olay listede en sondadır.', 'Önce ayakkabılarını giydi. Sonra ceketini aldı. En son okula yürüdü.'),
    ('orta', 'Yukarıdaki metinde sabah rutininin doğru sırası hangisidir?', 'Kalk - kahvaltı et - okula git', 'Okula git - kalk - kahvaltı et', 'Kahvaltı et - okula git - kalk', 'Önce uyanılır, sonra kahvaltı edilir, en son okula gidilir.', 'Sabah kalktı. Kahvaltı etti. Okula gitti.'),
    ('orta', 'Yukarıdaki numaralı olayların oluş sırası hangisidir?', 'II - III - I', 'I - II - III', 'III - I - II', 'Önce evden çıkılır, bisiklet sürülür, en son parka varılır.', 'I. Parka vardı.\nII. Evden çıktı.\nIII. Bisikletini sürdü.'),
    ('orta', 'Yukarıdaki sofra olaylarından hangisi en başta yapılmalıdır?', 'Yemeği pişirmek', 'Masayı kurmak', 'Sofraya oturmak', 'Yemek pişmeden masa kurulamaz; önce yemek pişirilmelidir.', 'I. Masayı kurdu.\nII. Yemeği pişirdi.\nIII. Sofraya oturdu.'),
    ('orta', 'Yukarıdaki olaylardan hangisi mantıklı sırada sona gelir?', 'Dinlenmek', 'Ödev yapmak', 'Ders çalışmak', 'Önce ders çalışılır, ödev yapılır, en son dinlenilir.', 'I. Ödevini yaptı.\nII. Ders çalıştı.\nIII. Dinlendi.'),
    ('orta', 'Yukarıdaki metinde proje sunumu hangi gün olmuştur?', 'Pazartesi', 'Salı', 'Çarşamba', 'Proje sunumu pazartesi günü gerçekleşmiştir.', 'Pazartesi sınıfta proje sundu. Salı günü öğretmeni övdü.'),
    ('orta', 'Yukarıdaki metinde denize girme olayı hangi mevsimde geçmiştir?', 'Yaz', 'Kış', 'Sonbahar', 'Yaz tatili ifadesi olayın yaz mevsiminde olduğunu gösterir.', 'Yaz tatilinde kuzenimle denize girdik. Akşamüstü kumsalda oyun oynadık.'),
    ('orta', 'Yukarıdaki metinde kedinin koşması hangi olaydan önce gerçekleşmiştir?', 'Mama verilmesi', 'Uyuması', 'Oyun oynaması', 'Önce kedi koşmuş, sonra mama verilmiştir.', 'Kedim miyavlayarak mutfağa koştu. Annem ona mama verdi.'),
    ('orta', 'Yukarıdaki metinde yola çıkmadan önce ne yapılmıştır?', 'Haritayı incelemiş', 'Dağa tırmanmış', 'Fotoğraf çekmiş', 'Yola çıkmadan önce harita incelenmiştir.', 'Önce haritayı inceledi. Sonra yola çıktı. En son dağın tepesine ulaştı.'),
    ('orta', 'Yukarıdaki metinde eve dönme olayı ne zaman gerçekleşmiştir?', 'Film bitince', 'Film başlamadan', 'Sabah erken', 'Film bitince ifadesi eve dönmenin ne zaman olduğunu söyler.', 'Cuma akşamı ailecek sinemaya gittik. Film bitince eve döndük.'),
    ('orta', 'Önce kar yağdı. Ardından çocuklar kardan adam yaptı. Kardan adam yapma hangi olaydan sonra gerçekleşmiştir?', 'Kar yağması', 'Kar erimesi', 'Güneş batması', 'Kar yağdıktan sonra çocuklar kardan adam yapmıştır.'),
    ('orta', 'Önce sepeti hazırladık. Sonra ormana yürüdük. Ormana yürümeden önce hangi iş yapılmıştır?', 'Sepet hazırlanmış', 'Piknik bitmiş', 'Uyku uyumuş', 'Ormana gitmeden önce sepet hazırlanmıştır.'),
    ('orta', 'Yukarıdaki cümlelerde önce gerçekleşen olay hangisidir?', '3', '1', '2', 'Ders başlama üçüncü olaydır.', '1) Okul zili çaldı. 2) Öğrenciler sınıfa girdi.'),
    ('orta', 'Yukarıdaki olaylar arasında sonraki olay hangisidir?', '3', '1', '2', 'Sebze toplama en son gerçekleşen olaydır.', '1) Tohumları toprağa koydu. 2) Bahçeyi suladı.'),
    ('orta', 'Önce elini kaldırdı. Sonra soruyu cevapladı. Soruyu cevaplamadan önce ne yapmıştır?', 'Elini kaldırmış', 'Tahtaya yazmış', 'Dışarı çıkmış', 'Soruyu cevaplamadan önce elini kaldırmıştır.'),
    ('orta', 'Önce marşı söyledik. Sonra bayrağı göndere çektik. Bayrağı çekme olayı hangi olaydan sonra gelmiştir?', 'Marş söyleme', 'Teneffüs', 'Yemek yeme', 'Marş söylendikten sonra bayrak göndere çekilmiştir.'),
    ('orta', 'Hikâyede olayları anlatırken hangi kelime sonraki olayı gösterir?', 'Sonra', 'Önce', 'Her zaman', 'Sonra kelimesi bir olaydan sonra gelen olayı gösterir.'),
    ('orta', 'Hikâyede olayları anlatırken hangi kelime ilk olayı gösterir?', 'Önce', 'Sonra', 'En son', 'Önce kelimesi ilk gerçekleşen olayı gösterir.'),
    ('orta', 'Aşağıdakilerden hangisi olay sırasını göstermek için kullanılır?', '1, 2, 3 numaraları', 'Renkler', 'Harfler', 'Numaralar olayların hangi sırayla olduğunu gösterir.'),
    ('orta', 'Hikâyede olayları karışık sırada anlatmak neden yanlıştır?', 'Dinleyici kafası karışır', 'Kitap kısalır', 'Resim azalır', 'Karışık sıra hikâyenin anlaşılmasını zorlaştırır.'),
    ('orta', 'Önce montunu giydi. Sonra dışarı çıktı. Dışarı çıkmadan önce ne yapmıştır?', 'Montunu giymiş', 'Televizyon izlemiş', 'Yemek yemiş', 'Dışarı çıkmadan önce mont giyilmiştir.'),
    ('orta', 'Önce öğretmen tahtaya yazdı. Sonra öğrenciler defterlerine geçti. Öğrenciler ne zaman defterlerine geçmiştir?', 'Öğretmen yazdıktan sonra', 'Öğretmen yazmadan önce', 'Dersten önce', 'Öğretmen yazdıktan sonra öğrenciler defterlerine geçmiştir.'),
    ('orta', 'Yukarıdaki numaralı olaylardan ilk sıradaki hangisidir?', '2', '1', '3', 'Zarfına koyma ikinci olaydır.', '1) Mektubu yazdı. 2) Zarfına koydu.'),
    ('orta', 'Yukarıdaki cümlelerde en son gerçekleşen olay hangisidir?', '3', '1', '2', 'Postaya verme en son gerçekleşen olaydır.', '1) Mektubu yazdı. 2) Zarfına koydu.'),
    ('orta', 'Hikâye yazarken olayları sıralamak hangi unsurla ilgilidir?', 'Olayların oluş sırası', 'Kitabın rengi', 'Yazarın yaşı', 'Olayların oluş sırası hikâyenin anlaşılması için önemlidir.'),
    # ── ZOR (50) ──
    ('zor', 'Yukarıdaki olayların mantıklı sırası hangisidir?', 'II - I - III', 'I - II - III', 'III - II - I', 'Önce ders çalışılır, ödev bitirilir, en son dinlenilir.', 'I. Defne ödevini bitirdi.\nII. Defne ders çalışmaya başladı.\nIII. Defne dinlenmek için müziği açtı.'),
    ('zor', 'Yukarıdaki alışveriş olaylarının doğru sırası hangisidir?', 'III - II - I', 'I - III - II', 'II - I - III', 'Önce evden çıkılır, marketten ekmek alınır, bisiklet park edilir.', 'I. Bisikletini park etti.\nII. Marketten ekmek aldı.\nIII. Evden çıktı.'),
    ('zor', 'Yukarıdaki metinde anlatım bozukluğu hangi sebepten kaynaklanır?', 'Olaylar karışık sırada', 'Metin çok kısa', 'Kahraman yok', 'Yemekte önce masaya oturulur, çorba içilir, en son eller yıkanır; verilen sıra mantıklı değildir.', 'I. Masaya oturdu.\nII. Ellerini yıkadı.\nIII. Çorbayı içti.'),
    ('zor', 'Yukarıdaki yemekte olayların doğru sırası hangisidir?', 'Masaya otur - çorba iç - el yıka', 'El yıka - çorba iç - masaya otur', 'Çorba iç - masaya otur - el yıka', 'Yemekte önce masaya oturulur, çorba içilir, en son eller yıkanır.', 'I. Masaya oturdu.\nII. Ellerini yıkadı.\nIII. Çorbayı içti.'),
    ('zor', 'Yukarıdaki sorulardan hangisi olay unsurunu buldurur?', 'III', 'I', 'II', 'III. soru ne oldu diye sorar; bu olay unsurunu buldurur.', 'I. Kim?\nII. Nerede?\nIII. Ne oldu?'),
    ('zor', 'Yukarıdaki sorulardan hangisi yer unsurunu buldurur?', 'II', 'I', 'III', 'II. soru nerede diye sorar; yer unsurunu buldurur.', 'I. Kim?\nII. Nerede?\nIII. Ne oldu?'),
    ('zor', 'Yukarıdaki ifadelerden hangisi hikâye unsuru değildir?', 'Dize', 'Kahraman', 'Zaman', 'Dize şiirin satırıdır; kahraman ve zaman hikâye unsurudur.', 'I. Kahraman\nII. Dize\nIII. Zaman'),
    ('zor', 'Yukarıdaki ifadelerden hangileri hikâye unsurudur?', 'Hepsi', 'Yalnız I', 'I ve II', 'Kahraman, yer ve olay hikâyenin temel unsurlarındandır.', 'I. Kahraman\nII. Yer\nIII. Olay'),
    ('zor', 'Yukarıdaki metinde kahraman kimdir?', 'Berk', 'Köy pazarı', 'Pazar sabahı', 'Berk olayları yaşayan kişidir.', 'Pazar sabahı Berk köy pazarına gitti. Sebze aldı, sonra dedesiyle çay içti. Akşam eve döndü.'),
    ('zor', 'Yukarıdaki metinde Berk nereye gitmiştir?', 'Köy pazarı', 'Berk', 'Dedesi', 'Köy pazarı olayın geçtiği yerdir.', 'Pazar sabahı Berk köy pazarına gitti. Sebze aldı, sonra dedesiyle çay içti. Akşam eve döndü.'),
    ('zor', "Yukarıdaki metinde Berk'in gezintisi hangi gün başlamıştır?", 'Pazar sabahı', 'Akşam', 'Salı', 'Pazar sabahı zaman unsurudur.', 'Pazar sabahı Berk köy pazarına gitti. Sebze aldı, sonra dedesiyle çay içti. Akşam eve döndü.'),
    ('zor', 'Yukarıdaki metinde sebze alma olayı hangi olaydan önce gerçekleşmiştir?', 'Dedesiyle çay içme', 'Eve dönme', 'Uyuma', 'Önce sebze alınmış, sonra dedesiyle çay içilmiştir.', 'Pazar sabahı Berk köy pazarına gitti. Sebze aldı, sonra dedesiyle çay içti. Akşam eve döndü.'),
    ('zor', 'Yukarıdaki metinde deney yapan kişiler kimdir?', 'Biz / sınıf', 'Öğretmen', 'Salı', 'Deneyi yapan kişiler biziz.', 'Salı günü sınıfta deney yaptık. Önce malzemeleri hazırladık. Sonra öğretmenimiz bize yardım etti.'),
    ('zor', 'Yukarıdaki metinde olay nerede geçmiştir?', 'Sınıf', 'Deney', 'Salı', 'Sınıf olayın geçtiği yerdir.', 'Salı günü sınıfta deney yaptık. Önce malzemeleri hazırladık. Sonra öğretmenimiz bize yardım etti.'),
    ('zor', 'Yukarıdaki metinde malzeme hazırlama olayı hangi olaydan önce gelmiştir?', 'Öğretmenin yardım etmesi', 'Deney yapılması', 'Teneffüs', 'Önce malzemeler hazırlanmış, sonra öğretmen yardım etmiştir.', 'Salı günü sınıfta deney yaptık. Önce malzemeleri hazırladık. Sonra öğretmenimiz bize yardım etti.'),
    ('zor', 'Yukarıdaki metinde üç olayın sırası doğru mudur?', 'Evet, sıra doğrudur', 'Hayır, tam tersi olmalı', 'Sıra önemsizdir', 'Önce yağmur, sonra ıslanma, en son eve koşma mantıklı bir sıradır.', 'Önce yağmur yağdı. Sonra sokaklar ıslandı. En son çocuklar evlere koştu.'),
    ('zor', 'Yukarıdaki metinde hangi olay yanlış sırada verilmiştir?', 'Diş fırçalamadan önce uyumak', 'Yatağa yatmak', 'Diş fırçalamak', 'Uyumadan önce dişler fırçalanmalıdır; sıra mantıklı değildir.', 'Önce uykuya daldı. Sonra dişlerini fırçaladı. En son yatağa yattı.'),
    ('zor', 'Yukarıdaki olayların oluş sırası hangisidir?', 'II - I - III', 'I - II - III', 'III - I - II', 'Önce zil çalar, öğrenciler sınıfa girer, ders başlar.', 'I. Okul zili çaldı.\nII. Öğrenciler sınıfa girdi.\nIII. Ders başladı.'),
    ('zor', 'Yukarıdaki bahçe olaylarının mantıklı sırası hangisidir?', 'I - II - III', 'III - I - II', 'II - III - I', 'Önce tohum ekilir, sulama yapılır, en son sebze toplanır.', 'I. Tohumları toprağa koydu.\nII. Bahçeyi suladı.\nIII. Sebzeleri topladı.'),
    ('zor', 'Yukarıdaki sorulardan hangisi kahramanı buldurur?', 'II', 'I', 'III', 'Kim sorusu kahramanı buldurur.', 'I. Ne zaman?\nII. Kim?\nIII. Nerede?'),
    ('zor', 'Yukarıdaki sorulardan hangisi zaman unsurunu buldurur?', 'I', 'II', 'III', 'Ne zaman sorusu zaman unsurunu buldurur.', 'I. Ne zaman?\nII. Kim?\nIII. Nerede?'),
    ('zor', 'Yukarıdaki kitap okuma olaylarının doğru sırası hangisidir?', 'II - I - III', 'I - II - III', 'III - II - I', 'Önce son sayfa okunur, kitap kapatılır, rafa konur.', 'I. Kitabı kapattı.\nII. Son sayfayı okudu.\nIII. Kitabı rafa koydu.'),
    ('zor', 'Yukarıdaki metinde kardan adam yapma olayı hangi olaydan sonra gerçekleşmiştir?', 'Kar yağması', 'Kar erimesi', 'Güneş batması', 'Kar yağınca çocuklar kardan adam yapmıştır.', 'Önce kar yağdı. Ardından çocuklar kardan adam yaptı. En son güneş çıkınca kar eridi.'),
    ('zor', 'Yukarıdaki metinde ormana yürümeden önce ne yapılmıştır?', 'Sepet hazırlanmış', 'Piknik bitmiş', 'Uyku uyumuş', 'Ormana yürümeden önce sepet hazırlanmıştır.', 'Cumartesi sabahı pikniğe gittik. Önce sepeti hazırladık. Sonra ormana yürüdük.'),
    ('zor', 'Yukarıdaki yemek olaylarından hangisi ilk sırada olmalıdır?', 'II', 'I', 'III', 'Önce yemek yenir, sonra tabak toplanır, en son el yıkanır.', 'I. Ellerini yıkadı.\nII. Yemeğini yedi.\nIII. Tabaklarını topladı.'),
    ('zor', 'Yukarıdaki yemek olaylarının doğru sırası hangisidir?', 'II - III - I', 'I - II - III', 'III - I - II', 'Önce yemek yenir, tabak toplanır, en son eller yıkanır.', 'I. Ellerini yıkadı.\nII. Yemeğini yedi.\nIII. Tabaklarını topladı.'),
    ('zor', 'Yukarıdaki metinde olayların sırası neden yanlıştır?', 'Yüzmeden önce havlu alınmış', 'Metin çok uzun', 'Kahraman yok', 'Yüzmeden önce havlu alınır; verilen sırada havlu alma yüzmeden sonra gelmiştir.', 'Önce denize girdi. Sonra havluyu aldı. En son güneşlendi.'),
    ('zor', 'Yukarıdaki plaj olaylarının doğru sırası hangisidir?', 'Havlu al - denize gir - güneşlen', 'Denize gir - havlu al - güneşlen', 'Güneşlen - denize gir - havlu al', 'Önce havlu alınır, denize girilir, sonra güneşlenilir.', 'Önce denize girdi. Sonra havluyu aldı. En son güneşlendi.'),
    ('zor', 'Yukarıdaki ifadelerden hangisi yer unsuru değildir?', 'Yıldızlar', 'Kamp alanı', 'Orman', 'Yıldızlar gök cismidir; kamp alanı ve orman yer unsuru olabilir.', 'I. Orman\nII. Kamp alanı\nIII. Yıldızlar'),
    ('zor', 'Yukarıdaki ifadelerden hangisi zaman unsuru değildir?', 'Kütüphane', 'Gece yarısı', 'Pazartesi', 'Kütüphane bir mekândır; gece yarısı ve pazartesi zaman unsuru olabilir.', 'I. Gece yarısı\nII. Pazartesi\nIII. Kütüphane'),
    ('zor', 'Yukarıdaki ifadelerden hangisi olay unsuru değildir?', 'Salı günü', 'Koşmak', 'Yüzmek', 'Salı günü zaman unsurudur; koşmak ve yüzmek olaydır.', 'I. Koşmak\nII. Salı günü\nIII. Yüzmek'),
    ('zor', 'Yukarıdaki metinde ilk olay hangisidir?', 'Okula gitmek', 'Ödev yapmak', 'Televizyon izlemek', 'Metinde önce okula gidilmiş, sonra ödev yapılmıştır.', 'Önce okula gitti. Sonra ödevini yaptı. En son televizyon izledi.'),
    ('zor', 'Yukarıdaki metinde en son olay hangisidir?', 'Televizyon izlemek', 'Okula gitmek', 'Ödev yapmak', 'En son televizyon izlenmiştir.', 'Önce okula gitti. Sonra ödevini yaptı. En son televizyon izledi.'),
    ('zor', 'Yukarıdaki olaylardan hangisi mantıksız sırada verilmiştir?', 'I', 'II', 'III', 'I. olayda önce yemek yenmeli, sonra tabak toplanmalıdır; ters verilmiştir.', 'I. Tabaklarını topladı.\nII. Yemeğini yedi.\nIII. Ellerini yıkadı.'),
    ('zor', 'Yukarıdaki tabak toplama olaylarının doğru sırası hangisidir?', 'II - I - III', 'I - II - III', 'III - II - I', 'Önce yemek yenir, sonra tabak toplanır, en son eller yıkanır.', 'I. Tabaklarını topladı.\nII. Yemeğini yedi.\nIII. Ellerini yıkadı.'),
    ('zor', 'Yukarıdaki kütüphane ziyareti hangi mekânda geçmiştir?', 'Kütüphane', 'Kitap', 'Cuma', 'Kütüphane olayın geçtiği yerdir.', 'Cuma öğleden sonra kütüphanede sessizce kitap okudu. Bitince kitabı rafa koydu.'),
    ('zor', 'Yukarıdaki metinde olay ne zaman geçmiştir?', 'Cuma öğleden sonra', 'Sabah', 'Gece', 'Cuma öğleden sonra zaman unsurudur.', 'Cuma öğleden sonra kütüphanede sessizce kitap okudu. Bitince kitabı rafa koydu.'),
    ('zor', 'Yukarıdaki metinde kitabı rafa koyma olayı hangi olaydan sonra gelmiştir?', 'Kitap okuma', 'Uyuma', 'Yemek yeme', 'Önce kitap okunmuş, sonra rafa konmuştur.', 'Cuma öğleden sonra kütüphanede sessizce kitap okudu. Bitince kitabı rafa koydu.'),
    ('zor', 'Yukarıdaki bahçe ekim olaylarının doğru sırası hangisidir?', 'I - II - III', 'III - I - II', 'II - III - I', 'Önce tohum ekilir, filiz çıkar, meyve toplanır.', 'I. Tohum ekti.\nII. Filiz çıktı.\nIII. Meyve topladı.'),
    ('zor', 'Yukarıdaki olaylardan hangisi en son gerçekleşir?', 'III', 'I', 'II', 'Meyve toplama en son gerçekleşen olaydır.', 'I. Tohum ekti.\nII. Filiz çıktı.\nIII. Meyve topladı.'),
    ('zor', 'Yukarıdaki sorulardan hangisi ne oldu sorusuna karşılık gelir?', 'III', 'I', 'II', 'Ne oldu sorusu olay unsurunu buldurur.', 'I. Kim?\nII. Ne zaman?\nIII. Ne oldu?'),
    ('zor', 'Yukarıdaki sorulardan hangisi nerede sorusuna karşılık gelir?', 'III', 'I', 'II', 'Nerede sorusu yer unsurunu buldurur.', 'I. Kim?\nII. Ne zaman?\nIII. Nerede?'),
    ('zor', 'Yukarıdaki metinde anlatım neden anlaşılmaz?', 'Olaylar mantıksız sırada', 'Metin çok kısa', 'Kahraman çok', 'Önce uyumalı, sonra yatak toplanmalı; verilen sıra mantıklı değildir.', 'Önce yatağa yattı. Sonra odasını topladı. En son uyudu.'),
    ('zor', 'Yukarıdaki metinde doğru sıra hangisidir?', 'Odayı topla - uyu - yatağa yat', 'Yatağa yat - odayı topla - uyu', 'Uyu - odayı topla - yatağa yat', 'Önce oda toplanır, uyuma ve yatağa yatma en son gelir.', 'Önce yatağa yattı. Sonra odasını topladı. En son uyudu.'),
    ('zor', 'Hikâyede olayları sıralarken en önemli kural hangisidir?', 'Oluş sırasına uymak', 'Rastgele anlatmak', 'Tersten anlatmak', 'Olaylar gerçekte oldukları sırayla anlatılmalıdır.'),
    ('zor', 'Hikâyede kahraman, yer, zaman ve olay unsurları bir arada ne sağlar?', 'Hikâyenin anlaşılmasını', 'Kitabın incelmesini', 'Resmin çizilmesini', 'Dört unsur bir arada hikâyenin tam anlaşılmasını sağlar.'),
    ('zor', 'Olay sırasını numaralandırmak hangi durumda en çok işe yarar?', 'Birden fazla olay anlatılırken', 'Tek cümle yazılırken', 'Başlık seçilirken', 'Birden fazla olay varken numaralar sırayı netleştirir.'),
    ('zor', 'Hikâyede önce-sonra ilişkisi bozulursa ne olur?', 'Dinleyici kafası karışır', 'Hikâye kısalır', 'Kahraman değişir', 'Sıra bozulunca olaylar birbirine karışır ve hikâye anlaşılmaz.'),
    ('zor', 'Aşağıdakilerden hangisi hikâye unsurlarını ve sıralamayı doğru açıklar?', 'Kahraman kişidir, olaylar oluş sırasına göre anlatılır', 'Yer kişi adıdır, sıra önemsizdir', 'Zaman olaydır, tersten anlatılır', 'Kahraman kişidir; olaylar oluş sırasına göre anlatılmalıdır.'),
    ('zor', 'Aşağıdakilerden hangisi olay sırası konusunda yanlıştır?', 'Olayları rastgele anlatmak daha iyidir', 'Önce ve sonra kelimeleri sırayı gösterir', 'Numaralar olay sırasını belirtir', 'Olayları rastgele anlatmak hikâyeyi anlaşılmaz yapar.'),
]

def get_questions() -> list[dict]:
    out = []
    for i, row in enumerate(_RAW, start=1):
        level, text, correct, w1, w2, exp = row[:6]
        premise = row[6] if len(row) > 6 else None
        out.append({
            "id": f"olay3_{i:03d}",
            "level": level,
            "premise": premise,
            "text": text,
            "correct": correct,
            "wrong1": w1,
            "wrong2": w2,
            "explanation": exp,
        })
    return out
