#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write duyu-explanations-v2.json with child-friendly 3rd-grade explanations."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "duyu-explanations-v2.json"

EXPLANATIONS = {
    "fen3_duyu_001": "Göz, kulak, burun, dil ve deri çevremizdeki sesleri, renkleri ve kokuları algılar. Bu organlara duyu organları denir. İç organlar ve hareket organları çevreyi hissetmez.",
    "fen3_duyu_002": "Beş temel duyumuz vardır: görme, işitme, koklama, tatma ve dokunma. Her birinin kendine ait bir organı vardır. Bu yüzden sayı 5'tir, 4 veya 6 değil.",
    "fen3_duyu_003": "Duyu organları bilgiyi toplar ve beyne gönderir. Ne gördüğümüzü, ne duyduğumuzu beyin anlar. Kalp kan pompalar, mide yemekleri sindirir.",
    "fen3_duyu_004": "Kalp kanı vücuda pompalayan bir iç organdır. Göz ve deri ise dış dünyayı algılayan duyu organlarıdır. Kalp duyu organı değildir.",
    "fen3_duyu_005": "Göz, kulak, burun ve dil başımızda bulunur. Deri ise tepeden tırnağa tüm vücudumuzu kaplar. Bu yüzden sadece başta olmayan duyu organı deridir.",
    "fen3_duyu_006": "Beş farklı duyumuz çevreyi renk, ses, koku, tat ve sıcaklık gibi özellikleriyle algılamamızı sağlar. Böylece tehlikeleri de fark ederiz. Güzel görünmek veya hızlı koşmak için değildir.",
    "fen3_duyu_007": "Göremeyen kişiler seslere ve dokunmaya daha çok dikkat eder. Yollarını bulmak için kulak ve derilerini daha çok kullanırlar. Tatma ve koklama bu işte o kadar yardımcı olmaz.",
    "fen3_duyu_008": "Çizgi film izlerken gözlerle resimleri görürüz, kulakla sesleri duyarız. Burun ve dil bu iş için kullanılmaz.",
    "fen3_duyu_009": "Yemeğin sıcağına dokunarak hissederiz, koku duyusu gerekmez. Bozuk yemek ve gaz kokusu ise burnumuzla algılanır.",
    "fen3_duyu_010": "Duyu organlarımızın sağlığı için temiz kalmalı ve tehlikeli maddelerden uzak durmalıyız. El yıkamak ve dikkatli olmak hepsine yardım eder. Çok yemek veya çok uyumak bununla ilgili değildir.",
    "fen3_duyu_011": "Renk, şekil ve büyüklük gözle görülür. Kulak ses duyar, deri dokunma hisseder.",
    "fen3_duyu_012": "Gökkuşağındaki renkler gözümüzle görülür. Dil tat alır, burun koku alır.",
    "fen3_duyu_013": "Dünyamızı görmek için ışığa ihtiyacımız vardır. Karanlık odada ışık olmadığı için gözlerimiz açık olsa bile bir şey göremeyiz. Ses veya sıcaklık görmeyi sağlamaz.",
    "fen3_duyu_014": "Kaşlar alından akan terin göze girmesini engeller. Kirpikler tozu tutar, gözyaşı ise gözü yıkar.",
    "fen3_duyu_015": "Gözyaşı gözü nemli tutar ve toz gibi yabancı maddeleri temizler. Sadece ağladığımızı göstermek veya rengi parlak yapmak için değildir.",
    "fen3_duyu_016": "Karanlıkta az ışık vardır. Göz bebeği büyüyerek daha fazla ışık almaya çalışır ve görmeyi kolaylaştırır. Korku veya uyku bunun nedeni değildir.",
    "fen3_duyu_017": "Göz kırpınca gözyaşı tüm göze yayılır. Böylece göz kurumaz ve temiz kalır. Kas güçlendirme veya renk görmek için değildir.",
    "fen3_duyu_018": "Havuç gibi A vitamini içeren besinler göz sağlığına iyidir. Karbonhidrat ve şeker göz için özel bir fayda sağlamaz.",
    "fen3_duyu_019": "Televizyona çok yakın bakmak gözleri yorar. 3-4 metre uzaktan izlemek gözümüzü korur. Burna değdirerek bakmak çok zararlıdır.",
    "fen3_duyu_020": "Kitabı gözümüze çok yakın tutmak gözü yorar. Yaklaşık 30-40 santimetre uzaklık en uygun mesafedir. Bir cetvel boyu kadar uzakta tutmak iyidir.",
    "fen3_duyu_021": "Güneşli günlerde Güneş'in parlak ışığı gözümüze zarar verebilir. Güneş gözlüğü bunu engeller. Bere ve kulaklık gözü korumaz.",
    "fen3_duyu_022": "Başkasının havlu veya gözlüğünde mikrop olabilir. Bu özellikle gözümüze bulaşır ve hastalık yapar. Burun ve kulak bu kadar kolay etkilenmez.",
    "fen3_duyu_023": "Göz ağrısı veya görme sorunu için göz doktoruna gideriz. Diş doktoru dişlerle, KBB uzmanı ise kulak ve burunla ilgilenir.",
    "fen3_duyu_024": "Net göremeyen kişiler doktorun verdiği numaralı gözlük veya lens takar. Büyüteç ve dürbün günlük hayatta bu iş için kullanılmaz.",
    "fen3_duyu_025": "Braille alfabesi kabartmalı noktalardan oluşur. Parmakla dokunarak okunur. İşaret dili elle konuşmak, Mors alfabesi ise sesle iletişim içindir.",
    "fen3_duyu_026": "Beyaz bastonla yolu dokerken dokunur ve ses çıkarırız. Böylece göremeyen kişiler yön bulur. Hızlı yürümek veya koku geliştirmek amacı değildir.",
    "fen3_duyu_027": "Renk körlüğü olan kişiler bazı renkleri ayırt edemez. Gece körlüğü karanlıkta görmeyi zorlaştırır. Miyop ise uzağı net görememektir.",
    "fen3_duyu_028": "Kirli ellerde mikrop vardır. Gözümüzü ovuşturursak mikrop bulaşır ve göz kızarır. Görme gücü artmaz, renk de değişmez.",
    "fen3_duyu_029": "Ekrana uzun süre bakmak gözü yorar. Ara sıra uzağa veya yeşilliklere bakmalıyız. Ovuşturmak veya daha yakına bakmak daha da yorar.",
    "fen3_duyu_030": "Trafik ışığının rengini gözümüzle görürüz. Kulak ses duyar, burun koku alır; renk onlara görünmez.",
    "fen3_duyu_031": "Uzağı göremeyen öğrenci tahtaya yakın oturmalıdır. Arka sırada yazıları okuyamaz. Ön sıra ona yardımcı olur.",
    "fen3_duyu_032": "Gözümüze toz kaçınca gözyaşı artar ve gözü yıkar. Tozu dışarı atar. Tozu içeride tutmaz veya buharlaştırmaz.",
    "fen3_duyu_033": "Toz gelince gözümüz kendiliğinden kapanır. Bu refleks gözü korur. Gözü kocaman açmak veya ağzı açmak doğru değildir.",
    "fen3_duyu_034": "Sağ elle yazan öğrencinin eli gölge yapmasın diye ışık soldan gelmelidir. Sağdan gelirse yazı karanlık kalır.",
    "fen3_duyu_035": "Karanlık odada sadece parlak ekrana bakmak gözü çok yorar. Hafif bir ışık açık olmalıdır. Zifiri karanlık veya çok parlak oda da uygun değildir.",
    "fen3_duyu_036": "Göze kimyasal veya cisim kaçınca bol temiz suyla yıkamalı ve doktora gitmeliyiz. Ovuşturmak veya peçete sokmak gözü daha çok yaralar.",
    "fen3_duyu_037": "Kuş sesi, müzik ve konuşma kulakla duyulur. Göz görür, burun koku alır.",
    "fen3_duyu_038": "İki kulak sayesinde sesin sağdan mı soldan mı geldiğini anlarız. Daha yüksek ses duymak veya gözlük takmak ana fayda değildir.",
    "fen3_duyu_039": "Kulak kepçesi dışarıdaki sesleri toplayıp kulak yoluna iletir. Huninin görevi budur. Sesi inceltmek veya soğuktan korumak asıl işi değildir.",
    "fen3_duyu_040": "Ses kulak yolundan geçince ince kulak zarına çarpar ve titreşir. Kulak kepçesi sesi toplar ama titreştirmez. Tat tomurcukları dilde bulunur.",
    "fen3_duyu_041": "Kulak kiri pislik değildir, kulak içini toz ve böcekten korur. Daha iyi duymak veya güzel koku vermek için değildir.",
    "fen3_duyu_042": "Kulak zarı sesi titreştirerek duymamızı sağlar. Zar yırtılırsa duyamayabiliriz. Daha iyi duymaya başlamayız.",
    "fen3_duyu_043": "İç kulaktaki yapılar dengemizi sağlar. Döndükten sonra başımız dönmesinin nedeni de budur. Sindirme ve renk görme kulakla ilgili değildir.",
    "fen3_duyu_044": "Çok gürültüde ağzımızı açarak kulak içindeki havayı dengeleriz. Böylece kulak zarı patlamaz. Göz kapatmak veya nefes tutmak bu işe yaramaz.",
    "fen3_duyu_045": "Çok yüksek ses iç kulağa zarar verir ve kalıcı işitme kaybı yapabilir. Görme veya tat alma bozulmaz.",
    "fen3_duyu_046": "Sürekli gürültü insanı yorar, stres yapar ve baş ağrıtır. Daha iyi görme veya kemik uzaması gürültünün sonucu değildir.",
    "fen3_duyu_047": "Kulağa kürdan veya kalem sokmak kulak zarına zarar verebilir. Yumuşak havluyla dış kulağı silmek güvenlidir.",
    "fen3_duyu_048": "Kulak ağrısı için Kulak Burun Boğaz doktoruna gideriz. Göz ve cildiye doktoru kulakla ilgilenmez.",
    "fen3_duyu_049": "Az duyan kişiler işitme cihazı takar. Bu cihaz sesi yükseltir. Müzik kulaklığı tıbbi amaçlı değildir.",
    "fen3_duyu_050": "İşitme engelliler eller ve mimiklerle işaret dili kullanır. Braille okumak için, Mors alfabesi ise telgraf içindir.",
    "fen3_duyu_051": "Köpek düdüğü insanın duyamadığı ince sesler çıkarır. Köpeklerin kulakları bu sesleri duyabilir. Büyük kulak kepçesi veya gözle görmek bunun nedeni değildir.",
    "fen3_duyu_052": "Banyodan sonra kulağın dışını yumuşak havluyla kurulamalıyız. Kulak çöpünü derine sokmak tehlikelidir.",
    "fen3_duyu_053": "Ağzı açınca boğazdan kulağa hava gider ve basıncı dengeler. Böylece kulak zarı patlamaz. Ses geri çıkmaz ve kulaklar kapanmaz.",
    "fen3_duyu_054": "Dudak okuma, konuşanın dudaklarını izleyerek ne dediğini anlamaktır. İşaret dili farklıdır, göz kırpma ise başka bir harekettir.",
    "fen3_duyu_055": "Hızlı dönünce iç kulaktaki denge sıvısı hâlâ hareket eder. Bu yüzden başımız döner. Gözyaşı ve mide sıvısı bunun nedeni değildir.",
    "fen3_duyu_056": "Korna sesini kulakla duyarız. Arkamızdaki aracı göremeyebiliriz ama sesten anlarız. Deri veya göz bu durumda yeterli olmaz.",
    "fen3_duyu_057": "Gürültü uykuyu bozar ve strese neden olur. Hayvanları da ürkütür. Daha güzel rüya görmek gürültünün sonucu değildir.",
    "fen3_duyu_058": "Her insanın sesi farklıdır. Kulak bu sesi duyar, beyin annemizin sesini hatırlar. Göz kapalıyken görme veya koku tatmayla ilgili değildir.",
    "fen3_duyu_059": "Kulak içi kulaklığı başkasıyla paylaşmak mikrop bulaştırır. Kulak enfeksiyonu yapabilir. Ses kalitesi veya göz sağlığı ana neden değildir.",
    "fen3_duyu_060": "Yüksek sesli işlerde koruyucu kulaklık kulak zarımızı korur. Müzik dinlemek veya soğuktan korunmak asıl amaç değildir.",
    "fen3_duyu_061": "Soğukta kulaklarımızı bereyle koruruz. Soğuk hava kulak ağrısı yapabilir. Daha iyi duymak için değildir.",
    "fen3_duyu_062": "Kulağa cisim kaçınca doktora gitmeliyiz. Kendimiz çıkarmaya çalışırsak daha derine itebiliriz.",
    "fen3_duyu_063": "Havadaki kokuları burnumuzla algılarız. Dil tat alır, göz görür.",
    "fen3_duyu_064": "Burnumuz nefes alıp vermemizi sağlar. Ayrıca koku da alır. Yemeği çiğnemek veya denge sağlamak burnun işi değildir.",
    "fen3_duyu_065": "Burun kılları havdaki toz ve mikropları tutar. Akciğerlere gitmesini engeller. Güzel koku veya nefes hızı için değildir.",
    "fen3_duyu_066": "Burun içindeki yapışkan sıvı burnu nemli tutar ve tozları yakalar. Bu sıvıya burun sümüğü denir. Koku duyusunu zayıflatmaz.",
    "fen3_duyu_067": "Soğuk havayı burnumuz ısıtır ve nemlendirerek akciğerlere gönderir. Böylece ciğerlerimiz hasta olmaz. Havayı dondurarak atmaz veya tamamen kapamaz.",
    "fen3_duyu_068": "Koku tanecikleri havada uçarak burnumuza gelir. Işık veya yuvarlanma kokuları taşımaz.",
    "fen3_duyu_069": "Gaz veya yanık kokusu tehlike işaretidir. Hemen dışarı çıkmamız gerekir. Pasta ve gül kokusu tehlike değildir.",
    "fen3_duyu_070": "Bilmediğimiz sıvılar zehirli olabilir. Koklamak akciğerlere zarar verir. Güzel kokmaması tek neden değildir.",
    "fen3_duyu_071": "Tuz ruhu gibi kimyasallar burnun koku alma yerlerine zarar verir. Kulak ve deri bu işte en çok etkilenmez.",
    "fen3_duyu_072": "Aynı kokuyu uzun süre alınca burnumuz yorulur ve kokuyu hissetmez. Bu koku yorgunluğudur. Parfüm bitmez, kulak bastırmaz.",
    "fen3_duyu_073": "Tat ve koku birlikte çalışır. Burun tıkalıyken yemeğin kokusunu alamayız, tadı da eksik gelir. Dilimiz dökülmez.",
    "fen3_duyu_074": "Burun kanarken başı hafif öne eğip burun kanatlarına baskı yapmalıyız. Başı geriye atmak kanı yutmamıza neden olur.",
    "fen3_duyu_075": "Köpeklerin burnu insanlardan çok daha güçlüdür. Enkaz altındaki kokuları bile alabilirler. Hızlı koşmak veya karanlıkta görme ana neden değildir.",
    "fen3_duyu_076": "Burnu mendille nazikçe silmek doğrudur. Parmağı içine sokmak veya kılları koparmak zarar verir.",
    "fen3_duyu_077": "Burun havayı temizler, ısıtır ve nemlendirir. Ağızdan nefes alınca soğuk ve kirli hava doğrudan gider. Diş kırılması veya yemek yiyememe ana neden değildir.",
    "fen3_duyu_078": "Burun kokuyu alır ama gül mü çöp mü olduğunu beyin anlar. Sadece burun veya göz yeterli değildir.",
    "fen3_duyu_079": "Burnumuz aynı kokudan yorulsa da yeni ve farklı kokuları hemen hisseder. Yanık kokusu buna örnektir. Hapşırma her zaman olmaz.",
    "fen3_duyu_080": "Polen gibi şeyler bazı kişilerde hapşırma ve burun akmasına neden olur. Buna alerji denir. Güneş çarpması veya gıda zehirlenmesi farklıdır.",
    "fen3_duyu_081": "Bozuk yemeğin kötü kokusu bizi uyarıır. Yemeyiz ve hastalanmayız. Daha çok sevmek veya burnun gelişmesi değildir.",
    "fen3_duyu_082": "Burnun içinde ince kan damarları vardır. Kalemle karıştırınca kolayca kanar. Damarsız değildir.",
    "fen3_duyu_083": "Hapşırma burna giren tozu ve tahriş edici maddeleri hızla dışarı atar. Koku almayı artırmak veya göz dinlendirmek için değildir.",
    "fen3_duyu_084": "Soğukta burnumuz havayı ısıtmak için daha çok kan alır. Bu yüzden kızarır. Donması veya kötü koku ana nedeni değildir.",
    "fen3_duyu_085": "Kokular eski anıları hatırlatır. Beyinde koku ile hafıza yerleri yakındır. Sadece eski kokuları almaz veya göz koku almaz.",
    "fen3_duyu_086": "Burna sert darbe nefes almayı ve koku almayı bozarabilir. Görme, işitme, tat ve dokunma doğrudan etkilenmez.",
    "fen3_duyu_087": "Burun tıkanıklığı için KBB doktoruna gideriz. Göz ve ortopedi doktoru burnun iç yapısıyla ilgilenmez.",
    "fen3_duyu_088": "Çok kirli havada burnumuz her şeyi temizleyemez. Zehirli gazlar akciğerlere ulaşır. Koku gelişmez, burnumuz sınırsız filtre değildir.",
    "fen3_duyu_089": "Tatlı, tuzlu, acı ve ekşi tadı dilimizle algılarız. Deri dokunur, burun koku alır.",
    "fen3_duyu_090": "Sıcak veya soğuk bir tat değildir, dokunma hissidir. Dört temel tat tatlı, tuzlu, acı ve ekşidir.",
    "fen3_duyu_091": "Dondurmanın soğuğunu dilimizin dokunma özelliğiyle hissederiz. Tat alma veya koku alma değildir.",
    "fen3_duyu_092": "Dilin üzerindeki küçük kabarcıklara tat tomurcukları denir. Tadı algılayıp beyne gönderirler. Tükürük bezleri su salgılar.",
    "fen3_duyu_093": "Tükürük yiyeceği ıslatır ve tadın alınmasını sağlar. Gözyaşı ve mide asidi bunun için değildir.",
    "fen3_duyu_094": "Dil konuşmamıza yardım eder, sesleri şekillendirir. Nefes alma ve koku ayırt etme dilin işi değildir.",
    "fen3_duyu_095": "Dil yiyeceği ağızda çevirir ve yutmamız için geri iter. Diş gibi kesmez, midede eritmez.",
    "fen3_duyu_096": "Çok sıcak veya soğuk yiyecekler dilin tat alma yerlerine zarar verir. Kulak ve göz bu durumda etkilenmez.",
    "fen3_duyu_097": "Çok asitli ve baharatlı yiyecekler dilin üzerindeki tat tomurcuklarını yıpratır. Tadımız zayıflar. Sadece midemize zarar değildir.",
    "fen3_duyu_098": "Tanımadığımız maddeler zehirli olabilir. Tatmak zehirlenmeye yol açar. Renk değişimi veya kötü tat tek neden değildir.",
    "fen3_duyu_099": "Günde iki kez dişlerimizi fırçalayıp dilimizi de hafifçe temizlemeliyiz. Ağız kokusunu önler. Sadece su veya sakız yeterli değildir.",
    "fen3_duyu_100": "Sağlıklı dil açık pembe renktedir. Beyaz veya sarı tabaka bakteri biriktiğini gösterir. Mavi renk doğal değildir.",
    "fen3_duyu_101": "Grip olunca burun tıkanır ve kokuyu alamayız. Yemekler de tatsız gelir. Dil tamamen uyuşmaz veya çorba zehirli olmaz.",
    "fen3_duyu_102": "Bozuk süt ekşi ve kötü tadar. Dilimiz bizi uyarır ve tükürürüz. Tatlı veya sıcak olması ana neden değildir.",
    "fen3_duyu_103": "Bebekler ağızlarıyla dokunarak ve tadarak tanır. Dil ve dudakları çok hassastır. Sürekli açlık veya diş temizliği ana neden değildir.",
    "fen3_duyu_104": "Dildeki beyaz veya sarı tabaka genelde temizlik yapılmadığını gösterir. Bakteriler birikmiştir. Çok süt içmek veya dilin iyi çalışması değildir.",
    "fen3_duyu_105": "Eskiden dilin bazı yerleri bazı tatları alır denirdi. Artık dilin her yerinin tüm tatları alabildiği biliniyor. Sadece uç tat almaz denimi yanlıştır.",
    "fen3_duyu_106": "Kalem çiğnemek mikrop bulaştırır ve dile yaralar açar. Tadının kötü olması veya renk değişimi ana tehlike değildir.",
    "fen3_duyu_107": "Güzel kokan parfüm yenmez, tadı kötüdür. Koku ve tat farklıdır. Çiçekler yenilebilir demek yanlıştır.",
    "fen3_duyu_108": "Ağız ve burun birbirine bağlıdır. Çok acı yiyince burnumuz da akar. Göz terlemesi veya sadece burunun ısınması ana neden değildir.",
    "fen3_duyu_109": "Çiğneyince yiyecek tükürükte daha çok çözünür. Tat tomurcukları daha çok tad alır. Sıcaklık artmaz, diş tat almaz.",
    "fen3_duyu_110": "Temiz suyun belirgin bir tadı yoktur. Ne tatlı, ne tuzlu, ne ekşidir. Tatsızdır.",
    "fen3_duyu_111": "Yaşlandıkça dildeki tat tomurcukları azalır. Yaşlılar yemekleri daha az tatlı bulur ve tuz ekler. Sadece tuzu sevmek veya diş beyazlatma değildir.",
    "fen3_duyu_112": "Ağız içi ve dil sorunları için diş hekimi veya KBB doktoruna gideriz. Göz ve cildiye doktoru bu alanda değildir.",
    "fen3_duyu_113": "Ağız içindeki küçük yaralara aft denir. Isırma veya mikrop nedeniyle olur. Çürük veya göz nezlesi farklıdır.",
    "fen3_duyu_114": "Elma ile soğanı kokuları ayırırız. Burun tıkalı olunca bu kokuları alamayız, tatlar karışır. Göz kapalıyken dil çalışmaz demek yanlıştır.",
    "fen3_duyu_115": "Deri tüm vücudu kaplar. Sertlik, yumuşaklık ve sıcaklığı hissederiz. Göz ve burun bunları algılamaz.",
    "fen3_duyu_116": "Deri en büyük duyu organıdır. Başından ayağına her yeri kaplar. Göz ve karaciğer bu kadar geniş değildir.",
    "fen3_duyu_117": "Gözler kapalıyken taş sert, pamuk yumuşaktır deriyle anlarız. Görme ve koku bu bilgi için gerekmez.",
    "fen3_duyu_118": "Sobanın sıcağını veya kışın soğuğunu derimizle hissederiz. Burun ve göz ısıyı bu şekilde algılamaz.",
    "fen3_duyu_119": "Kanı pompalamak kalbin işidir. Deri bizi korur, mikrop girmesini engeller ve dokunmayı sağlar.",
    "fen3_duyu_120": "Terleyince vücut serinler ve fazla su atılır. Derinin hem ısıyı dengelediğini hem de atık attığını gösterir. Kan üretmez.",
    "fen3_duyu_121": "Parmak uçlarımızda sinirler çok fazladır. En ince dokunuşları orada hissederiz. Sırt ve topuk daha az hassastır.",
    "fen3_duyu_122": "Sıcak çaydanlığa dokununca acı hissedip elimizi çekeriz. Böylece daha fazla yanmaktan korunuruz. Isıtmak veya ölçmek değildir.",
    "fen3_duyu_123": "Banyo yaparak derideki kir ve teri temizleriz. Deri hava alır. Güneşte beklemek veya dar kıyafet yardımcı olmaz.",
    "fen3_duyu_124": "Güneş kremi deriyi Güneş'in zararlı ışınlarından korur. Ağrı kesici veya kolonya bunun yerine kullanılmaz.",
    "fen3_duyu_125": "Bıçak ve makas deriyi keser, en çok deriye zarar verir. Kulak ve dil doğrudan kesilmez.",
    "fen3_duyu_126": "Açık yarada mikrop içeri girer. Deri vücudu zırh gibi korur, yara bu zırhı deler. Sadece çirkin görünüm değildir.",
    "fen3_duyu_127": "Derinin kurumaması için bol su içmeliyiz. Gerekirse nemlendirici kullanırız. Güneşte çok beklemek veya banyo yapmamak kurutur.",
    "fen3_duyu_128": "Yazın pamuklu ve açık renkli kıyafetler teri emer ve serin tutar. Naylon ve kalın yün deriyi boğar.",
    "fen3_duyu_129": "Parmak uçlarındaki deri kıvrımları her insanda farklıdır. Buna parmak izi denir. Ayak izi veya göz izi farklıdır.",
    "fen3_duyu_130": "Deri hastalıkları için cildiye doktoruna gideriz. Göz ve kalp doktoru ciltle ilgilenmez.",
    "fen3_duyu_131": "Soğukta tüylerimiz diken diken olur, bu derinin tepkisidir. Deri soğuğu hisseder ve ısı kaybını azaltmaya çalışır. Göz ve mide bunu yapmaz.",
    "fen3_duyu_132": "Ellerimize mikrop bulaşır çünkü her yere dokunuruz. Su ve sabunla yıkamak en önemli kuraldır. Sürekli krem veya eldiven giyinmek temel kural değildir.",
    "fen3_duyu_133": "Ayak tabanı sürekli sürtünür ve basınç görür. Deri kendini korumak için kalınlaşır ve nasırlaşır. Soğuk veya ayakkabı giymek ana neden değildir.",
    "fen3_duyu_134": "Karanlıkta göremediğimiz için ellerimizle yoklayarak yürürüz. Bu dokunma duyusudur. Görme ve tat bu işte yardımcı olmaz.",
    "fen3_duyu_135": "Cildin sağlıklı olması için bol su ve vitaminli meyve-sebze gerekir. Çikolata, cips ve asitli içecek cildi zayıflatır.",
    "fen3_duyu_136": "Havlu, tarak ve iç çamaşırı kişiseldir. Paylaşırsak deri hastalıkları bulaşır. Kıyafet giymemek veya başkasının kıyafetini giymek doğru değildir.",
    "fen3_duyu_137": "Kimyasallar deriyi yakar. Koruyucu plastik eldiven takmalıyız. Güneş gözlüğü ve yün eldiven yeterli değildir.",
    "fen3_duyu_138": "Sokak hayvanına dokunduktan sonra ellerimizi yıkamalıyız. Üzerlerinde mikrop olabilir. Kıyafete silmek veya başka hayvana dokunmak tehlikelidir.",
    "fen3_duyu_139": "Bebeklerin derisi hassastır. Anneler suyun sıcaklığını dirsekle veya elin tersiyle dener. Dokunarak yanıp yanmayacağını anlarlar. Koku veya temizlik için değildir.",
    "fen3_duyu_140": "Deri acıyı hisseder ve beyne gönderir. Asıl anlamlandıran ve 'canım yandı' diyen organ beyindir. Kalp ve mide bunu yapmaz.",
}


def main() -> None:
    expected = [f"fen3_duyu_{i:03d}" for i in range(1, 141)]
    missing = [k for k in expected if k not in EXPLANATIONS]
    extra = [k for k in EXPLANATIONS if k not in expected]
    if missing:
        raise SystemExit(f"Missing IDs: {missing}")
    if extra:
        raise SystemExit(f"Extra IDs: {extra}")

    ordered = {k: EXPLANATIONS[k] for k in expected}
    OUT.write_text(
        json.dumps(ordered, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(ordered)} explanations to {OUT}")


if __name__ == "__main__":
    main()
